[project]
name = "ComfyUI-Global-Translation"
description = "全球语言翻译插件 — 全面、智能、兼容的 ComfyUI 界面多国语言翻译解决方案。"
version = "3.1.1"
license = {file = "LICENSE"} 

[project.urls]
Repository = "https://github.com/a63976659/ComfyUI-Global-Translation"
#  Used by Comfy Registry https://registry.comfy.org

[tool.comfy]
PublisherId = "a63976659"
DisplayName = "ComfyUI-Global-Translation"
Icon = ""
includes = [] 
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility

