# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ComfyUI-GeometryPack Contributors

"""Individual UV unwrap backend nodes (hidden from UI, invoked via unified UV Unwrap node)."""

from .xatlas import NODE_CLASS_MAPPINGS as XATLAS_MAPS, NODE_DISPLAY_NAME_MAPPINGS as XATLAS_DISP
from .libigl_lscm import NODE_CLASS_MAPPINGS as LSCM_MAPS, NODE_DISPLAY_NAME_MAPPINGS as LSCM_DISP
from .libigl_harmonic import NODE_CLASS_MAPPINGS as HARM_MAPS, NODE_DISPLAY_NAME_MAPPINGS as HARM_DISP
from .libigl_arap import NODE_CLASS_MAPPINGS as ARAP_MAPS, NODE_DISPLAY_NAME_MAPPINGS as ARAP_DISP

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(XATLAS_MAPS)
NODE_CLASS_MAPPINGS.update(LSCM_MAPS)
NODE_CLASS_MAPPINGS.update(HARM_MAPS)
NODE_CLASS_MAPPINGS.update(ARAP_MAPS)

NODE_DISPLAY_NAME_MAPPINGS.update(XATLAS_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(LSCM_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(HARM_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(ARAP_DISP)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
