import { app } from "../../scripts/app.js";
import { api } from "../../scripts/api.js";

const CLASS_NAME = "IAMCCS_CineShotboardPlannerV3B";
const VERSION = "2026-08-28-autonomous-1";
const cls = (node) => String(node?.comfyClass || node?.type || "");
const getWidget = (node, name) => (node.widgets || []).find((item) => item?.name === name);
const clamp = (value, lo, hi) => Math.max(lo, Math.min(hi, Number(value) || 0));
const uid = () => `clip_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`;
const paths = (node) => String(getWidget(node, "image_paths")?.value || "").split(/\r?\n/).map(v => v.trim()).filter(Boolean);
const preview = (path) => `/api/iamccs/cine/view_image?path=${encodeURIComponent(path)}`;

function hide(widget) { if (widget) { widget.hidden = true; widget.computeSize = () => [0, -4]; } }
function readJson(value, fallback = {}) { try { const out = JSON.parse(String(value || "")); return out && typeof out === "object" ? out : fallback; } catch (_) { return fallback; } }
function boxAt(object, time) {
    const frames = [...(object?.keyframes || [])].sort((a, b) => Number(a.time) - Number(b.time));
    if (!frames.length) return null;
    if (time <= frames[0].time) return frames[0].box;
    if (time >= frames.at(-1).time) return frames.at(-1).box;
    for (let i = 0; i < frames.length - 1; i++) { const a=frames[i],b=frames[i+1]; if(time<a.time||time>b.time)continue; const r=(time-a.time)/Math.max(.000001,b.time-a.time); return a.box.map((v,j)=>Number(v)+(Number(b.box[j])-Number(v))*r); }
    return frames[0].box;
}
function button(label, onclick, kind="normal") { const out=document.createElement("button");out.textContent=label;const p=kind==="gold"?["#876324","#edc358"]:kind==="red"?["#713333","#db7777"]:["#244855","#64aabd"];out.style.cssText=`height:30px;padding:0 11px;border:1px solid ${p[1]};border-radius:5px;background:${p[0]};color:#f5fbfd;font:700 11px Arial;cursor:pointer;white-space:nowrap`;out.onclick=onclick;return out;}
async function upload(files) { const result=[];for(const file of Array.from(files||[])){const body=new FormData();body.append("image",file);body.append("type","input");body.append("overwrite","false");const response=await api.fetchApi("/upload/image",{method:"POST",body});if(!response?.ok)throw new Error(`upload failed: ${response?.status}`);const data=await response.json();result.push(data.subfolder?`${data.subfolder}/${data.name}`:data.name);}return result; }

function mount(node) {
    if (cls(node)!==CLASS_NAME || node._iamccsV3BAutonomousRoot) return;
    ["global_prompt","timeline_data","duration_seconds","frame_rate","image_paths","image_width","image_height","image_resize_method","image_multiple_of","img_compression","bbox_enabled","bbox_project_json"].forEach(name=>hide(getWidget(node,name)));
    node.title="SHOTBOARD V3B · LTX 2.5 BBOX AUTONOMOUS";node.color="#153846";node.bgcolor="#091c25";
    let timeline=readJson(getWidget(node,"timeline_data")?.value,{});timeline.schema||="iamccs.ltx25.shotboard.v3b.timeline";timeline.schema_version||=1;timeline.segments||=[];timeline.duration_seconds=Number(timeline.duration_seconds||getWidget(node,"duration_seconds")?.value||5);timeline.frame_rate=Number(timeline.frame_rate||getWidget(node,"frame_rate")?.value||24);
    let playFrame=0,selectedId=null,playing=false,playTimer=null,viewMode="overlay";
    const totalFrames=()=>Math.max(1,Math.ceil(Math.max(0,timeline.duration_seconds*timeline.frame_rate-1)/8)*8+1);
    const project=()=>timeline.bboxControl||timeline.bbox_control||readJson(getWidget(node,"bbox_project_json")?.value,{});
    const activeSegment=()=>[...timeline.segments].reverse().find(seg=>playFrame>=Number(seg.start||0)&&playFrame<Number(seg.start||0)+Number(seg.length||1));
    const activePath=()=>{const seg=activeSegment();return seg?(String(seg.imageTruthPath||seg.imageFile||"")||paths(node)[Math.max(0,Number(seg.ref||1)-1)]||""):(paths(node)[0]||"");};

    const root=document.createElement("div");root.dataset.iamccsV3bAutonomous=VERSION;root.style.cssText="width:100%;height:100%;box-sizing:border-box;padding:10px;border:1px solid #50bdd5;border-radius:8px;background:linear-gradient(145deg,#102d39,#111b24 58%,#211d17);color:#eef8fb;font:12px Arial;overflow:auto";
    const header=document.createElement("div");header.style.cssText="display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-bottom:8px";const brand=document.createElement("strong");brand.textContent="V3B · LTX 2.5 OBJECT & BBOX SHOTBOARD";brand.style.cssText="color:#8deaff;margin-right:auto;letter-spacing:.7px";const files=document.createElement("input");files.type="file";files.accept="image/*";files.multiple=true;files.style.display="none";const addImages=button("+ Images",()=>{files.value="";files.click();});const director=button("BBox Director",()=>node._iamccsOpenLTX25BBoxDirector?.(),"gold");const play=button("▶ Play",()=>{playing=!playing;play.textContent=playing?"■ Stop":"▶ Play";clearInterval(playTimer);if(playing)playTimer=setInterval(()=>{playFrame=(playFrame+1)%totalFrames();draw();},1000/timeline.frame_rate);});const overlay=button("Overlay",()=>{viewMode="overlay";draw();});const signal=button("Control",()=>{viewMode="signal";draw();});header.append(brand,addImages,director,play,overlay,signal,files);root.append(header);
    const settings=document.createElement("div");settings.style.cssText="display:grid;grid-template-columns:1fr 100px 84px 92px 92px;gap:7px;margin-bottom:8px";const prompt=document.createElement("textarea");prompt.value=String(getWidget(node,"global_prompt")?.value||"");prompt.placeholder="Global cinematic prompt";prompt.style.cssText="height:54px;resize:vertical;background:#07141b;color:#edfaff;border:1px solid #365c69;border-radius:5px;padding:7px";const num=(label,value,min,step)=>{const box=document.createElement("label");box.style.cssText="color:#9eb7c0;font-size:10px";const input=document.createElement("input");input.type="number";input.value=value;input.min=min;input.step=step;input.style.cssText="display:block;width:100%;box-sizing:border-box;margin-top:3px;background:#07141b;color:#fff;border:1px solid #365c69;border-radius:4px;padding:6px";box.append(label,input);return[box,input];};const [durationBox,durationInput]=num("SECONDS",timeline.duration_seconds,.1,.1),[fpsBox,fpsInput]=num("FPS",timeline.frame_rate,1,1),[widthBox,widthInput]=num("WIDTH",timeline.image_width||getWidget(node,"image_width")?.value||768,64,32),[heightBox,heightInput]=num("HEIGHT",timeline.image_height||getWidget(node,"image_height")?.value||448,64,32);settings.append(prompt,durationBox,fpsBox,widthBox,heightBox);root.append(settings);
    const main=document.createElement("div");main.style.cssText="display:grid;grid-template-columns:190px minmax(500px,1fr);gap:9px";const slots=document.createElement("div");slots.style.cssText="border:1px solid #365c69;border-radius:6px;background:#0a171e;padding:6px;min-height:390px";const slotTitle=document.createElement("strong");slotTitle.textContent="IMAGE SLOTS";slotTitle.style.color="#9addec";const slotList=document.createElement("div");slotList.style.cssText="display:flex;flex-direction:column;gap:6px;margin-top:7px";slots.append(slotTitle,slotList);const work=document.createElement("div");work.style.cssText="display:flex;flex-direction:column;gap:8px;min-width:0";const monitor=document.createElement("div");monitor.style.cssText="position:relative;height:300px;border:1px solid #477786;border-radius:6px;background:#000;overflow:hidden";const monitorImage=document.createElement("img");monitorImage.style.cssText="position:absolute;inset:0;width:100%;height:100%;object-fit:contain;opacity:.76";const monitorCanvas=document.createElement("canvas");monitorCanvas.style.cssText="position:absolute;inset:0;width:100%;height:100%;pointer-events:none";const monitorLabel=document.createElement("div");monitorLabel.style.cssText="position:absolute;left:6px;bottom:5px;padding:3px 6px;background:#000c;border-radius:3px;color:#d8f5fc;font-size:10px";monitor.append(monitorImage,monitorCanvas,monitorLabel);const timelineHeader=document.createElement("div");timelineHeader.style.cssText="display:flex;align-items:center;gap:8px";const timelineTitle=document.createElement("strong");timelineTitle.textContent="IMAGE TIMELINE · drag clips / drag edges";timelineTitle.style.color="#9addec";const playInfo=document.createElement("span");playInfo.style.cssText="margin-left:auto;color:#f1bd5a;font-variant-numeric:tabular-nums";timelineHeader.append(timelineTitle,playInfo);const track=document.createElement("div");track.style.cssText="position:relative;height:92px;border:1px solid #466975;border-radius:6px;background:repeating-linear-gradient(90deg,#101e25 0,#101e25 39px,#1a3039 40px);overflow:hidden;touch-action:none";work.append(monitor,timelineHeader,track);main.append(slots,work);root.append(main);
    const domWidget=node.addDOMWidget("V3B Autonomous","iamccs_ltx25_v3b_autonomous",root,{serialize:false});domWidget.computeSize=width=>[Math.max(940,Number(width||940)),720];node._iamccsV3BAutonomousRoot=root;node.setSize([Math.max(980,node.size?.[0]||0),Math.max(780,node.size?.[1]||0)]);

    function write(){timeline.duration_seconds=Number(durationInput.value||5);timeline.frame_rate=Number(fpsInput.value||24);timeline.image_width=Number(widthInput.value||768);timeline.image_height=Number(heightInput.value||448);timeline.bboxControl=project();timeline.bbox_control=timeline.bboxControl;getWidget(node,"timeline_data").value=JSON.stringify(timeline);getWidget(node,"duration_seconds").value=timeline.duration_seconds;getWidget(node,"frame_rate").value=timeline.frame_rate;getWidget(node,"image_width").value=timeline.image_width;getWidget(node,"image_height").value=timeline.image_height;node.graph?.setDirtyCanvas(true,true);}
    prompt.oninput=()=>{getWidget(node,"global_prompt").value=prompt.value;write();};[durationInput,fpsInput,widthInput,heightInput].forEach(input=>input.onchange=()=>{write();playFrame=Math.min(playFrame,totalFrames()-1);draw();});
    files.onchange=async()=>{try{const uploaded=await upload(files.files),all=[...paths(node),...uploaded];getWidget(node,"image_paths").value=all.join("\n");let cursor=timeline.segments.reduce((end,item)=>Math.max(end,Number(item.start||0)+Number(item.length||1)),0);uploaded.forEach(path=>{const ref=all.indexOf(path)+1,start=Math.min(cursor,totalFrames()-1),length=Math.max(1,Math.min(timeline.frame_rate*2,totalFrames()-start));timeline.segments.push({id:uid(),type:"image",start,length,ref,imageFile:path,imageTruthPath:path,label:path.split(/[\\/]/).pop(),prompt:""});cursor+=length;});write();draw();}catch(error){console.error("[IAMCCS V3B] image upload failed",error);alert(`V3B image upload failed: ${error.message||error}`);}};
    function renderSlots(){slotList.replaceChildren();paths(node).forEach((path,index)=>{const card=document.createElement("div");card.draggable=true;card.style.cssText="display:grid;grid-template-columns:70px 1fr auto;gap:6px;align-items:center;padding:4px;border:1px solid #35505b;border-radius:5px;background:#101f27;cursor:grab";const img=document.createElement("img");img.src=preview(path);img.style.cssText="width:70px;height:45px;object-fit:cover;border-radius:3px";const name=document.createElement("span");name.textContent=`${index+1} · ${path.split(/[\\/]/).pop()}`;name.style.cssText="font-size:10px;overflow:hidden;word-break:break-all";const remove=button("×",()=>{const remaining=paths(node).filter((_,i)=>i!==index);getWidget(node,"image_paths").value=remaining.join("\n");timeline.segments=timeline.segments.filter(seg=>Number(seg.ref)!==index+1).map(seg=>({...seg,ref:Number(seg.ref)>index+1?Number(seg.ref)-1:Number(seg.ref)}));write();draw();},"red");remove.style.padding="0 7px";card.addEventListener("dragstart",e=>e.dataTransfer.setData("text/iamccs-v3b-ref",String(index+1)));card.append(img,name,remove);slotList.append(card);});if(!paths(node).length){const empty=document.createElement("div");empty.textContent="Use + Images to create slots";empty.style.cssText="padding:20px 5px;color:#78929d;text-align:center";slotList.append(empty);}}
    track.addEventListener("dragover",e=>e.preventDefault());track.addEventListener("drop",e=>{e.preventDefault();const ref=Number(e.dataTransfer.getData("text/iamccs-v3b-ref"));if(!ref)return;const rect=track.getBoundingClientRect(),start=Math.round(clamp((e.clientX-rect.left)/rect.width,0,.999)*totalFrames()),path=paths(node)[ref-1];timeline.segments.push({id:uid(),type:"image",start,length:Math.max(1,Math.min(timeline.frame_rate*2,totalFrames()-start)),ref,imageFile:path,imageTruthPath:path,label:path.split(/[\\/]/).pop(),prompt:""});write();draw();});track.addEventListener("pointerdown",e=>{if(e.target!==track)return;const rect=track.getBoundingClientRect();playFrame=Math.round(clamp((e.clientX-rect.left)/rect.width,0,1)*(totalFrames()-1));draw();});
    function renderTimeline(){track.replaceChildren();for(const segment of timeline.segments){const clip=document.createElement("div"),left=Number(segment.start||0)/totalFrames()*100,width=Math.max(.8,Number(segment.length||1)/totalFrames()*100);clip.style.cssText=`position:absolute;left:${left}%;width:${width}%;top:25px;height:46px;box-sizing:border-box;border:2px solid ${segment.id===selectedId?"#ffd166":"#62bdd1"};border-radius:5px;background:linear-gradient(180deg,#2b6c7d,#183b47);color:#fff;overflow:hidden;cursor:grab;user-select:none`;const label=document.createElement("span");label.textContent=`${segment.label||"image"} · ${segment.start}f +${segment.length}f`;label.style.cssText="display:block;padding:14px 10px 0;white-space:nowrap;font-size:10px";const lh=document.createElement("i"),rh=document.createElement("i");[lh,rh].forEach(h=>h.style.cssText="position:absolute;top:0;width:7px;height:100%;background:#d6f6ff66;cursor:ew-resize");lh.style.left="0";rh.style.right="0";clip.append(label,lh,rh);const begin=(event,mode)=>{event.preventDefault();event.stopPropagation();selectedId=segment.id;const x=event.clientX,s=Number(segment.start||0),l=Number(segment.length||1);const move=ev=>{const d=Math.round((ev.clientX-x)/track.getBoundingClientRect().width*totalFrames());if(mode==="move")segment.start=clamp(s+d,0,totalFrames()-l);if(mode==="left"){const n=clamp(s+d,0,s+l-1);segment.length=l+(s-n);segment.start=n;}if(mode==="right")segment.length=clamp(l+d,1,totalFrames()-s);write();renderTimeline();drawMonitor();};const end=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",end);};window.addEventListener("pointermove",move);window.addEventListener("pointerup",end);};clip.onpointerdown=e=>begin(e,"move");lh.onpointerdown=e=>begin(e,"left");rh.onpointerdown=e=>begin(e,"right");clip.ondblclick=()=>{timeline.segments=timeline.segments.filter(item=>item.id!==segment.id);write();draw();};track.append(clip);}const head=document.createElement("div");head.style.cssText=`position:absolute;left:${playFrame/totalFrames()*100}%;top:0;bottom:0;width:2px;background:#ffbd4d;pointer-events:none`;track.append(head);playInfo.textContent=`${playFrame} / ${totalFrames()}f · ${(playFrame/timeline.frame_rate).toFixed(2)}s`;}
    function drawMonitor(){const path=activePath();if(monitorImage.dataset.path!==path){monitorImage.dataset.path=path;monitorImage.src=path?preview(path):"";}monitorImage.style.display=viewMode==="overlay"?"block":"none";monitorLabel.textContent=path?`${viewMode.toUpperCase()} · ${path.split(/[\\/]/).pop()}`:`${viewMode.toUpperCase()} · no active image`;const rect=monitorCanvas.getBoundingClientRect(),dpr=devicePixelRatio||1;monitorCanvas.width=Math.max(1,Math.round(rect.width*dpr));monitorCanvas.height=Math.max(1,Math.round(rect.height*dpr));const ctx=monitorCanvas.getContext("2d");ctx.scale(dpr,dpr);ctx.clearRect(0,0,rect.width,rect.height);if(viewMode==="signal"){ctx.fillStyle="#000";ctx.fillRect(0,0,rect.width,rect.height);}const time=clamp(playFrame/totalFrames(),0,1);(project().objects||[]).forEach((object,index)=>{if(object.enabled===false||time<Number(object.start_time||0)||time>Number(object.end_time??1))return;const box=boxAt(object,time);if(!box)return;const x=box[0]*rect.width,y=box[1]*rect.height,w=(box[2]-box[0])*rect.width,h=(box[3]-box[1])*rect.height;ctx.strokeStyle=viewMode==="signal"?"#fff":object.color||["#72dff5","#ff7896","#ffd166"][index%3];ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=2;ctx.strokeRect(x,y,w,h);ctx.beginPath();ctx.arc(x+w/2,y+h/2,2.5,0,Math.PI*2);ctx.fill();if(viewMode==="overlay"){ctx.font="11px Arial";ctx.fillRect(x,Math.max(0,y-17),Math.max(60,ctx.measureText(object.name||"Object").width+12),17);ctx.fillStyle="#061016";ctx.fillText(object.name||"Object",x+5,Math.max(12,y-5));}});}
    function draw(){renderSlots();renderTimeline();drawMonitor();}
    node._iamccsV3BTimelineController={getPlayFrame:()=>playFrame,setPlayFrame:frame=>{playFrame=clamp(Math.round(frame),0,totalFrames()-1);draw();},getTotalFrames:totalFrames,getFps:()=>timeline.frame_rate,getTimeline:()=>timeline,writeTimeline:write,getReferencePaths:()=>paths(node),previewUrlForPath:preview};new ResizeObserver(drawMonitor).observe(monitor);write();draw();
}

function scanGraph() {
    for (const node of app.graph?._nodes || []) {
        if (cls(node) === CLASS_NAME && !node._iamccsV3BAutonomousRoot) mount(node);
    }
}
console.log(`[IAMCCS V3B] Autonomous UI loaded ${VERSION}`);
app.registerExtension({
    name:"iamccs.ltx25.shotboard.v3b.autonomous",
    async setup(){ setTimeout(scanGraph,0); setTimeout(scanGraph,500); setTimeout(scanGraph,2000); },
    async beforeRegisterNodeDef(nodeType,nodeData){
        if(String(nodeData?.name||nodeData?.class_type||"")!==CLASS_NAME)return;
        console.log("[IAMCCS V3B] autonomous node type registered");
        const original=nodeType.prototype.onNodeCreated;
        nodeType.prototype.onNodeCreated=function(...args){const result=original?.apply(this,args);setTimeout(()=>mount(this),0);return result;};
    },
    async nodeCreated(node){if(cls(node)===CLASS_NAME){console.log("[IAMCCS V3B] nodeCreated mount",node.id);setTimeout(()=>mount(node),0);}},
    async loadedGraphNode(node){if(cls(node)===CLASS_NAME){console.log("[IAMCCS V3B] loadedGraphNode mount",node.id);setTimeout(()=>mount(node),0);}},
    async afterConfigureGraph(){setTimeout(scanGraph,0);setTimeout(scanGraph,250);},
});
