python = "3.11"

[target.linux-64.dependencies]
xorg-libsm = "*"     # libSM.so.6 required by bpy

[dependencies]
av = "*"
numpy = ">=1.23,<2"   # bpy 4.2 compiled against numpy 1.x
tqdm = "*"

[pypi-dependencies]
bpy = ">=4.2"
trimesh = "*"