import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const source = await readFile(new URL("../js/minimax_h3_director.js", import.meta.url), "utf8");
assert.match(source, /refModLabel\.textContent = "REFMOD"/, "Director exposes a dedicated REFMOD button");
assert.match(source, /refModActiveBadge\.textContent = `\$\{active\} active`/, "button reports the active RefMod count");
assert.match(source, /ds-h3-refmod-badge/, "active count uses a dedicated green badge");
assert.match(source, /mode\(\) === "REF2VA"/, "RefMod controls are restricted to REF2VA");
assert.match(source, /\/dasiwa\/refmods/, "overlay uses the metadata-only route");
assert.match(source, /function openRefModOverlay\(trigger\)/, "button opens a separate RefMod overlay");
assert.match(source, /ds-h3-refmod-overlay/, "RefMods render in a fixed overlay instead of the node");
assert.doesNotMatch(source, /createElement\("details"\)/, "RefMods do not expand an in-node details widget");
const scalingIndex = source.indexOf('addDropdown("INPUT SCALING"');
const buttonIndex = source.indexOf('refModLabel.textContent = "REFMOD"');
assert.ok(scalingIndex >= 0 && buttonIndex > scalingIndex, "REFMOD button is created after INPUT SCALING");
assert.match(source, /1\. Choose a saved reference\. 2\. Enable it and set its influence\. 3\. Click INSERT IN PROMPT to insert its full expanded reference text—e\.g\. <Video 1>: digital animation, \.\.\.—/, "overlay explains the three-step full-reference-text insertion workflow with a concrete example");
assert.match(source, /Reference library/, "overlay explains the saved reference selector");
assert.match(source, /Reference strength/, "overlay explains strength");
assert.match(source, /Use reference/, "overlay explains the enabled toggle");
assert.match(source, /Prompt description/, "overlay explains workflow-owned descriptions");
assert.match(source, /grid-template-columns:140px minmax\(180px,1fr\) minmax\(220px,1\.25fr\)/, "every overlay field uses the same label/control/help columns");
assert.match(source, /function insertExpandedRefMod\(textarea, slot\)/, "all insertion entry points use one full-reference-text inserter");
assert.match(source, /expansions\[row\.slot\] = description \? `\$\{tag\}: \$\{description\}` : tag/, "insertion expands a RefMod to its native label plus description");
assert.match(source, /insertAtCursor\(textarea, expansion \+ " "\)/, "expanded reference text is inserted at the cursor");
assert.match(source, /insertExpandedRefMod\(promptField, row\.slot\)/, "overlay insert button writes the full expanded reference text");
assert.match(source, /insertExpandedRefMod\(target, n\)/, "REF2VA prompt-builder insert button writes the full expanded reference text");
assert.match(source, /Array\.isArray\(entry\.kinds\)/, "bundle member kinds are expanded in prompt labels");
assert.match(source, /cardHead\.append\(cardTitle, alias, insert, remove\)/, "insert action sits beside the RefMod alias");

assert.doesNotMatch(source, /field\("Prompt tag"/, "insert is not rendered as a separate misaligned field row");
assert.match(source, /\.ds-h3-refmod-field:has\(textarea\)\{[^}]*min-height:92px/, "description rows reserve enough height for their textarea");
assert.match(source, /\.ds-h3-refmod-field textarea\{[^}]*height:72px/, "description fields keep a stable uncropped height");
assert.match(source, /event\.key\.toLowerCase\(\) !== "r"/, "ComfyUI's R reload invalidates the RefMod library");
assert.match(source, /activeRefModLibraryRefresh\?\.\(\)/, "R refreshes an already-open RefMod overlay");
assert.match(source, /state\.refmods/, "selections persist in timeline_data state");
assert.match(source, /<RefMod \$\{row\.slot\}>/, "stable aliases use the stored slot");
assert.match(source, /strength\.step = "0\.05"/, "strength uses the planned step");
assert.match(source, /Math\.max\(0, Math\.min\(1,/, "typed strength is clamped to the valid backend range");
assert.match(source, /event\.key === "Tab"/, "modal traps keyboard focus");
assert.match(source, /trigger\?\.focus\(\)/, "modal restores focus to its trigger");
assert.match(source, /activeRefModOverlayCleanup\?\.\(\)/, "node cleanup closes any owned overlay");
assert.match(source, /const slot = Math\.max\(0, Number\(row\.slot \|\| 1\) - 1\)/, "each selected RefMod maps its 1-based alias to its matching timeline slot");
assert.match(source, /type, value: row\.name, slot, start: slot/, "RefMod timeline clips use their native lane type and fixed slot position");
assert.match(source, /select\.onchange = \(\) => \{[\s\S]*?emit\(\); redraw\(\); render\(\); \};/, "selecting a RefMod immediately re-renders its occupied timeline slot");
assert.match(source, /enabled\.onchange = \(\) => \{[\s\S]*?emit\(\); redraw\(\); render\(\); \};/, "enabling or disabling a RefMod immediately updates its timeline slot");
assert.match(source, /item\._audioEcho \|\| item\._isRefMod/, "RefMod timeline clips are read-only and cannot be dragged");
assert.doesNotMatch(source, /ComfyUI-MiniMaxH3Mod/, "frontend has no upstream dependency");
console.log("Director RefMod lazy submenu contract: PASS");
