# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ComfyUI-GeometryPack Contributors

"""
Individual smoothing backend nodes (hidden from UI, invoked via unified Smooth Mesh node).
"""

from .taubin import NODE_CLASS_MAPPINGS as TAU_MAPS, NODE_DISPLAY_NAME_MAPPINGS as TAU_DISP
from .laplacian import NODE_CLASS_MAPPINGS as LAP_MAPS, NODE_DISPLAY_NAME_MAPPINGS as LAP_DISP
from .hc_laplacian import NODE_CLASS_MAPPINGS as HC_MAPS, NODE_DISPLAY_NAME_MAPPINGS as HC_DISP
from .trimesh_laplacian import NODE_CLASS_MAPPINGS as TL_MAPS, NODE_DISPLAY_NAME_MAPPINGS as TL_DISP
from .trimesh_taubin import NODE_CLASS_MAPPINGS as TT_MAPS, NODE_DISPLAY_NAME_MAPPINGS as TT_DISP

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(TAU_MAPS)
NODE_CLASS_MAPPINGS.update(LAP_MAPS)
NODE_CLASS_MAPPINGS.update(HC_MAPS)
NODE_CLASS_MAPPINGS.update(TL_MAPS)
NODE_CLASS_MAPPINGS.update(TT_MAPS)

NODE_DISPLAY_NAME_MAPPINGS.update(TAU_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(LAP_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(HC_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(TL_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(TT_DISP)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
