[project]
name = "comfyui-wan-vace-prep"
description = "ComfyUI nodes designed to help make common video editing tasks with Wan VACE less complicated."
version = "1.0.18"
license = { text = "MIT" }

dependencies = []

[project.urls]
Repository = "https://github.com/stuttlepress/ComfyUI-Wan-VACE-Prep"

[tool.comfy]
PublisherId = "stuttlepress"
DisplayName = "ComfyUI Wan VACE Prep"
Icon = "https://raw.githubusercontent.com/stuttlepress/ComfyUI-Wan-VACE-Prep/main/assets/icon.png"
