from .nodes import NODE_CLASS_MAPPINGS as NODES_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as NODES_DISPLAY_MAPPINGS

# Import Chinese tools nodes
try:
    from .chinese_tools import NODE_CLASS_MAPPINGS as CHINESE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CHINESE_DISPLAY_MAPPINGS
    # Merge the mappings
    NODE_CLASS_MAPPINGS = {**NODES_MAPPINGS, **CHINESE_MAPPINGS}
    NODE_DISPLAY_NAME_MAPPINGS = {**NODES_DISPLAY_MAPPINGS, **CHINESE_DISPLAY_MAPPINGS}
except Exception as e:
    print(f"⚠️ Failed to load Chinese tools nodes: {e}")
    NODE_CLASS_MAPPINGS = NODES_MAPPINGS
    NODE_DISPLAY_NAME_MAPPINGS = NODES_DISPLAY_MAPPINGS

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']