# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ComfyUI-GeometryPack Contributors

"""Individual Blender remeshing backend nodes (hidden, invoked via unified Remesh node)."""

from .voxel import NODE_CLASS_MAPPINGS as VOXEL_MAPS, NODE_DISPLAY_NAME_MAPPINGS as VOXEL_DISP
from .sharp import NODE_CLASS_MAPPINGS as SHARP_MAPS, NODE_DISPLAY_NAME_MAPPINGS as SHARP_DISP
from .blocks import NODE_CLASS_MAPPINGS as BLOCKS_MAPS, NODE_DISPLAY_NAME_MAPPINGS as BLOCKS_DISP

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(VOXEL_MAPS)
NODE_CLASS_MAPPINGS.update(SHARP_MAPS)
NODE_CLASS_MAPPINGS.update(BLOCKS_MAPS)

NODE_DISPLAY_NAME_MAPPINGS.update(VOXEL_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(SHARP_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(BLOCKS_DISP)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
