import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";

const source = await readFile(
    new URL("../web/h3_project_asset_manager.js", import.meta.url), "utf8",
);

assert.match(source, /MiniMaxH3ProjectAssetManager/);
assert.match(source, /ComfyUI input/);
assert.match(source, /Create a project asset from the selected source/);
assert.doesNotMatch(source, /Server path/);
assert.doesNotMatch(source, /Absolute server media path/);
assert.match(source, /H3 backups/);
assert.match(source, /\["project", "Other Run"\]/);
assert.match(source, /Other Run reads the live Asset Carousel/);
assert.match(source, /source_project: item\.source_project/);
assert.match(source, /No matching assets were found in another Run/);
assert.match(source, /project-assets\/upload/);
assert.match(source, /Drop image, video, or audio files here/);
assert.match(source, /Drop to create assets/);
assert.match(source, /function hasDraggedFiles\(event\)/);
assert.match(source, /if \(state\.dragging\) return false/);
assert.match(source, /image\.draggable = false/);
assert.match(source, /dataTransfer\?\.types/);
assert.match(source, /includes\("Files"\)/);
assert.match(source, /event\.dataTransfer\.dropEffect = "copy"/);
assert.match(source, /carousel\.addEventListener\("dragenter"/);
assert.match(source, /carousel\.addEventListener\("dragleave"/);
assert.match(source, /uploadFiles\(files, \{dropped: true\}\)/);
assert.match(source, /dropController\.abort\(\)/);
assert.match(source, /Created .* project assets from dropped files/);
assert.match(source, /project-assets\/import/);
assert.match(source, /project-assets\/update/);
assert.match(source, /project-assets\/duplicate/);
assert.match(source, /Duplicate project…/);
assert.match(source, /function duplicateAssetProject\(\)/);
assert.match(source, /project-assets\/duplicate-project/);
assert.match(source, /new_project: newProject/);
assert.match(source, /Generated clips, checkpoints, and rendered outputs are not copied/);
assert.match(source, /the current Run remains selected/);
assert.match(source, /project-assets\/derive/);
assert.match(source, /project-assets\/folder/);
assert.match(source, /project-assets\/reorder/);
assert.match(source, /project-assets\/delete/);
assert.match(source, /Saving asset order/);
assert.match(source, /card\.draggable = true/);
assert.match(source, /dragstart/);
assert.match(source, /dragover/);
assert.match(source, /aria-label", "Delete asset/);
assert.match(source, /window\.confirm/);
assert.match(source, /The original file you imported is not touched/);
assert.match(source, /h3pa-action-label", "Asset/);
assert.match(source, /aria-label", "Move asset earlier/);
assert.match(source, /aria-label", "Move asset later/);
assert.match(source, /video\.controls = true/);
assert.match(source, /video\.preload = "metadata"/);
assert.match(source, /h3pa-audio-preview/);
assert.match(source, /Saved with the project · generation unchanged/);
assert.match(source, /Paste lyrics, then stamp each line while the song plays/);
assert.match(source, /Lyrics are project notes stored with this audio asset/);
assert.match(source, /Stamp selected line/);
assert.match(source, /formatLyricsTimestamp\(audio\.currentTime\)/);
assert.match(source, /asset, \{lyrics: nextLyrics\}/);
assert.match(source, /renderAfter: false/);
assert.match(source, /Ctrl\/Cmd\+Enter saves immediately/);
assert.match(source, /serialize: false/);
assert.match(source, /getMinHeight: \(\) => 560/);
assert.match(source, /flex:1 1 auto/);
assert.doesNotMatch(source, /dom\.computeSize/);
assert.match(source, /state\.media\?\.pause/);
assert.match(source, /Unassigned/);
assert.match(source, /reference_slots/);
assert.match(source, /Choose from ComfyUI Input/);
assert.match(source, /slot_id/);
assert.match(source, /node\.onExecuted/);
assert.match(source, /widget\(node, "run_name"\)/);
assert.match(source, /SEMANTIC_SETTING_WIDGETS/);
assert.match(source, /"semantic_anchor_size", "semantic_anchor_mode"/);
assert.match(source, /h3_show_semantic_anchor_settings/);
assert.match(source, /Hide semantic anchor settings/);
assert.match(source, /Show semantic anchor settings/);
assert.match(source, /refreshSemanticSettingVisibility\(this\)/);
assert.match(source, /placeholder = "Run name"/);
assert.match(source, /choose an existing Asset Carousel project/);
assert.match(source, /const projectMenu = el\("select", "h3pa-project-menu"\)/);
assert.match(source, /Switch Asset Carousel project/);
assert.match(source, /function refreshProjectSuggestions\(\)/);
assert.match(source, /project-assets\/projects/);
assert.match(source, /projectMenu\.replaceChildren\(projectMenuPlaceholder\)/);
assert.match(source, /function switchProject\(selectedProject\)/);
assert.match(source, /state\.projectNames\.has\(selectedProject\)/);
assert.match(source, /syncDownstreamPlan\(node, selectedProject\)/);
assert.match(source, /const draft = String\(runNameInput\.value \|\| ""\)/);
assert.match(source, /runNameWidget\.value = draft/);
assert.match(source, /if \(!switchProject\(project\(\)\)\) void refresh\(\)/);
assert.match(source, /event\.key !== "Enter"/);
assert.match(source, /runNameInput\.blur\(\)/);
assert.doesNotMatch(source, /setTimeout\(refresh, 400\)/);
assert.match(source, /asset\?\.role === "semantic_anchor" \? "#" : "@"/);
assert.doesNotMatch(source, /if \(asset\._unresolved\) return false/);
assert.match(source, /if \(filter === "image"\) return asset\.role === "picture"/);
assert.match(source, /selectedUnassignedSlot\(\)/);
assert.match(source, /state\.bindingSlot = selectedUnassignedSlot\(\)/);
assert.match(source, /asset, "thumbnail"/);
assert.match(source, /Light previews/);
assert.match(source, /Full previews/);
assert.match(source, /Display quality for this Carousel only/);
assert.match(source, /Generation always uses the original stored asset/);
assert.match(source, /Available to prompts/);
assert.match(source, /Scene prompts still control where it is used/);
assert.match(source, /Selected timeline source/);
assert.match(source, /without exporting its Source Timeline/);
assert.match(source, /tagged audio reference/);
assert.match(source, /Audio use/);
assert.match(source, /Tagged clip \(@tag\)/);
assert.match(source, /Tagged timeline slice \(@tag\)/);
assert.match(source, /Project timeline source/);
assert.match(source, /No @tag is required/);
assert.match(source, /whether scenes use it as generation reference audio/);
assert.match(source, /whether it becomes the final soundtrack/);
assert.doesNotMatch(source, /unprompted sampling/);
assert.match(source, /requires Chain Policy Source reference=on/);
assert.match(source, /Chain Policy Source reference and Final audio remain authoritative/);
assert.match(source, /Catalog tag/);
assert.match(source, /Asset use/);
assert.match(source, /role\.title = VIDEO_ROLE_HELP\[asset\.role\]/);
assert.match(source, /el\("small", "h3pa-help", VIDEO_ROLE_HELP\[asset\.role\]\)/);
assert.match(source, /timelineHelp\.textContent = TIMELINE_MODE_HELP\[timeline\.value\]/);
assert.match(source, /editor\.append\(timelineHelp\)/);
assert.match(source, /\.h3pa-help\{[^}]*white-space:normal/);
assert.match(source, /motion transfer, not pose extraction/);
assert.match(source, /reduces source appearance influence/);
assert.doesNotMatch(source, /Extracts only the pose/);
assert.match(source, /Align audio reference/);
assert.match(source, /align_audio_reference: false/);
assert.match(source, /width:min\(760px,calc\(100vw - 32px\)\)/);
assert.match(source, /height:min\(520px,calc\(100vh - 48px\)\)/);
assert.match(source, /state\.previewMode === "full" \? "original" : "poster"/);
assert.match(source, /downstreamPlanRunName\(node\)/);
assert.match(source, /sequence !== refreshSequence \|\| project\(\) !== requestedProject/);
assert.match(source, /Enter a Run name, or connect this node to a named Plan/);
assert.match(source, /function adoptConnectedRunName\(\)/);
assert.match(source, /function scheduleGraphRunNameSync\(\)/);
assert.match(source, /\[0, 50, 200, 750\]/);
assert.match(source, /node\.onConnectionsChange/);
assert.match(source, /nodeClass\.prototype\.onGraphConfigured/);
assert.match(source, /async afterConfigureGraph\(\)/);
assert.match(source, /position:absolute;inset:0/);
assert.match(source, /function partialExecutionId\(node\)/);
assert.match(source, /app\.queuePrompt\(0, 1, \[partialExecutionId\(node\)\]\)/);
assert.match(source, /operation_json/);
assert.match(source, /Asset-only model upscale queued/);
assert.match(source, /Edit \/ upscale/);
assert.match(source, /Coordinates are oriented source-image pixels/);
assert.match(source, /Start centered crop/);
assert.match(source, /Drag anywhere to draw a crop/);
assert.match(source, /function cornerPoints/);
assert.match(source, /mode: "create"/);
assert.match(source, /function clampCrop\(preference = "size"\)/);
assert.match(source, /pointerdown/);
assert.match(source, /ArrowLeft/);
assert.match(source, /Target megapixels/);
assert.match(source, /let requestedMegapixels = /);
assert.match(source, /megapixelInput\.value = String\(requestedMegapixels\)/);
assert.doesNotMatch(source, /megapixelInput\.value = targetMp/);
assert.match(source, /requestedMegapixels, outputRatio\(\), outputMultiple/);
assert.match(source, /Output multiple/);
assert.match(source, /h3pa-mp-presets\{display:grid;grid-template-columns:repeat\(6/);
assert.match(source, /h3pa-snap-options\{display:grid;grid-template-columns:repeat\(5/);
assert.match(source, /\["Off", 1\]/);
assert.match(source, /\["64", 64\]/);
assert.match(source, /Reset all/);
assert.match(source, /function resetImageEditor/);
assert.match(source, /Lock output aspect ratio/);
assert.match(source, /Changing output width updates height/);
assert.match(source, /coupledOutputDimensions/);
assert.match(source, /Connected model input/);
assert.match(source, /Final saved asset/);
assert.match(source, /model runs at its native scale before the final fit/);
assert.match(source, /Output dimensions are multiples of/);
assert.match(source, /Presentation only\. Folder membership never changes prompts/);
assert.match(source, /without copying media bytes/);
assert.match(source, /No folder/);
assert.match(source, /h3pa-folder-tools/);
assert.match(source, /h3pa-folder-mosaic/);
assert.match(source, /function folderCard\(folder, previewAssets, totalCount\)/);
assert.match(source, /h3_project_asset_expanded_folders/);
assert.match(source, /function setFolderExpanded\(folderId, expanded\)/);
assert.match(source, /Manage folders…/);
assert.match(source, /Drag an asset here to move it into this folder/);
assert.match(source, /updateAsset\(asset, \{folder_id: folderId\}\)/);
assert.match(source, /carousel\.querySelectorAll/);
assert.doesNotMatch(source, /All folders/);
assert.doesNotMatch(source, /const folders = el\("div", "h3pa-folders"\)/);
assert.match(source, /h3pa-action-primary/);
assert.match(source, /h3pa-action-manage/);
assert.match(source, /publishProjectAssetCatalogChanged/);
assert.match(source, /publishProjectAssetCatalogChanged\(node, state\.catalog\)/);
assert.match(source, /serializedProjectAssetCatalog/);
assert.match(source, /hydrateSerializedCatalog/);
assert.match(source, /cached project assets/);
assert.match(source, /serializedProjectAssetIdentity/);
assert.match(source, /function restoreConfiguredProjectIdentity\(\)/);
assert.match(source, /refreshSequence \+= 1;\s*runNameInput\.value = configuredProject/);
assert.match(source, /node\._h3ProjectAssetRefresh\(\{fromConfiguration: true\}\)/);
assert.match(source, /_h3ProjectAssetRefresh\?\.\(\{\s*fromConfiguration: true/);

console.log("H3 Project Asset Carousel: metadata slots, binding, sources, lazy media, editing, and cleanup pass");
