from .starvae_ltxv_save import NODE_CLASS_MAPPINGS as SAVE_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SAVE_DISPLAY_MAPPINGS
from .starvae_ltxv_load import NODE_CLASS_MAPPINGS as LOAD_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOAD_DISPLAY_MAPPINGS
from .star_ltx_video_settings import NODE_CLASS_MAPPINGS as VIDEO_SETTINGS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_SETTINGS_DISPLAY_MAPPINGS
from .ltx_image_cut import NODE_CLASS_MAPPINGS as IMAGE_CUT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_CUT_DISPLAY_MAPPINGS
from .star_multi_inputs_to_one import NODE_CLASS_MAPPINGS as MULTI_INPUT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MULTI_INPUT_DISPLAY_MAPPINGS
from .star_ltxv_get_last_frame import NODE_CLASS_MAPPINGS as GET_LAST_FRAME_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GET_LAST_FRAME_DISPLAY_MAPPINGS
from .star_ltxv_load_last_image import NODE_CLASS_MAPPINGS as LOAD_LAST_IMAGE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOAD_LAST_IMAGE_DISPLAY_MAPPINGS
from .star_video_joiner import NODE_CLASS_MAPPINGS as VIDEO_JOINER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_JOINER_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **SAVE_NODE_MAPPINGS,
    **LOAD_NODE_MAPPINGS,
    **VIDEO_SETTINGS_MAPPINGS,
    **IMAGE_CUT_MAPPINGS,
    **MULTI_INPUT_MAPPINGS,
    **GET_LAST_FRAME_MAPPINGS,
    **LOAD_LAST_IMAGE_MAPPINGS,
    **VIDEO_JOINER_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **SAVE_DISPLAY_MAPPINGS,
    **LOAD_DISPLAY_MAPPINGS,
    **VIDEO_SETTINGS_DISPLAY_MAPPINGS,
    **IMAGE_CUT_DISPLAY_MAPPINGS,
    **MULTI_INPUT_DISPLAY_MAPPINGS,
    **GET_LAST_FRAME_DISPLAY_MAPPINGS,
    **LOAD_LAST_IMAGE_DISPLAY_MAPPINGS,
    **VIDEO_JOINER_DISPLAY_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
