"""Single source of truth for supported MOSS model roles and download layouts."""

MOSS_MODEL_SPECS = {
    "MOSS-TTS-Local-Transformer": {
        "repo_id": "OpenMOSS-Team/MOSS-TTS-Local-Transformer",
        "architecture": "local",
        "role": "tts",
        "display": "MOSS-TTS Local 1.7B",
        "description": "MOSS-TTS Local 1.7B - smaller/faster model",
        "codec_model": "MOSS-Audio-Tokenizer",
        "sample_rate": 24000,
        "audio_temperature": 1.0,
        "audio_top_p": 0.95,
        "audio_top_k": 50,
        "audio_repetition_penalty": 1.1,
        "max_new_tokens": 4096,
        "required_files": [
            "config.json", "generation_config.json", "processor_config.json", "tokenizer.json",
            "model.safetensors.index.json", "model-00001-of-00002.safetensors",
            "model-00002-of-00002.safetensors",
        ],
    },
    "MOSS-TTS-v1.5": {
        "repo_id": "OpenMOSS-Team/MOSS-TTS-v1.5",
        "architecture": "delay",
        "role": "tts",
        "display": "MOSS-TTS Delay 8B v1.5",
        "description": "MOSS-TTS Delay 8B v1.5 - recommended production checkpoint",
        "codec_model": "MOSS-Audio-Tokenizer",
        "sample_rate": 24000,
        "audio_temperature": 1.7,
        "audio_top_p": 0.8,
        "audio_top_k": 25,
        "audio_repetition_penalty": 1.0,
        "max_new_tokens": 4096,
        "required_files": [
            "config.json", "processor_config.json", "tokenizer.json", "model.safetensors.index.json",
            "model-00001-of-00004.safetensors", "model-00002-of-00004.safetensors",
            "model-00003-of-00004.safetensors", "model-00004-of-00004.safetensors",
        ],
    },
    "MOSS-TTS": {
        "repo_id": "OpenMOSS-Team/MOSS-TTS",
        "architecture": "delay",
        "role": "tts",
        "display": "MOSS-TTS Delay 8B 1.0",
        "description": "MOSS-TTS Delay 8B 1.0 - original long-form checkpoint",
        "codec_model": "MOSS-Audio-Tokenizer",
        "sample_rate": 24000,
        "audio_temperature": 1.7,
        "audio_top_p": 0.8,
        "audio_top_k": 25,
        "audio_repetition_penalty": 1.0,
        "max_new_tokens": 4096,
        "required_files": [
            "config.json", "processor_config.json", "tokenizer.json", "model.safetensors.index.json",
            "model-00001-of-00004.safetensors", "model-00002-of-00004.safetensors",
            "model-00003-of-00004.safetensors", "model-00004-of-00004.safetensors",
        ],
    },
    "MOSS-TTSD-v1.0": {
        "repo_id": "OpenMOSS-Team/MOSS-TTSD-v1.0",
        "architecture": "ttsd",
        "role": "dialogue",
        "display": "MOSS-TTSD v1.0 Dialogue 8B",
        "description": "MOSS-TTSD v1.0 Delay 8B - native multi-speaker dialogue model",
        "codec_model": "MOSS-Audio-Tokenizer",
        "sample_rate": 24000,
        "audio_temperature": 1.1,
        "audio_top_p": 0.9,
        "audio_top_k": 50,
        "audio_repetition_penalty": 1.1,
        "max_new_tokens": 4096,
        "required_files": [
            "config.json", "generation_config.json", "processor_config.json", "tokenizer.json",
            "model.safetensors.index.json", "model-00001-of-00004.safetensors",
            "model-00002-of-00004.safetensors", "model-00003-of-00004.safetensors",
            "model-00004-of-00004.safetensors",
        ],
    },
    "MOSS-VoiceGenerator": {
        "repo_id": "OpenMOSS-Team/MOSS-VoiceGenerator",
        "architecture": "delay",
        "role": "voice_design",
        "display": "MOSS VoiceGenerator 1.7B",
        "description": "MOSS VoiceGenerator 1.7B - reference-free voice design",
        "codec_model": "MOSS-Audio-Tokenizer",
        "sample_rate": 24000,
        "audio_temperature": 1.5,
        "audio_top_p": 0.6,
        "audio_top_k": 50,
        "audio_repetition_penalty": 1.1,
        "max_new_tokens": 4096,
        "required_files": [
            "config.json", "processor_config.json", "tokenizer.json", "model.safetensors",
        ],
    },
    "MOSS-SoundEffect": {
        "repo_id": "OpenMOSS-Team/MOSS-SoundEffect",
        "architecture": "delay",
        "role": "sound_effects",
        "display": "MOSS SoundEffect 8B v1",
        "description": "MOSS SoundEffect v1 - autoregressive environmental and action sound generation",
        "codec_model": "MOSS-Audio-Tokenizer",
        "sample_rate": 24000,
        "audio_temperature": 1.5,
        "audio_top_p": 0.6,
        "audio_top_k": 50,
        "audio_repetition_penalty": 1.2,
        "max_new_tokens": 4096,
        "required_files": [
            "config.json", "processor_config.json", "tokenizer.json", "model.safetensors.index.json",
            "model-00001-of-00004.safetensors", "model-00002-of-00004.safetensors",
            "model-00003-of-00004.safetensors", "model-00004-of-00004.safetensors",
        ],
    },
}

MOSS_CODEC_SPECS = {
    "MOSS-Audio-Tokenizer": {
        "repo_id": "OpenMOSS-Team/MOSS-Audio-Tokenizer",
        "description": "MOSS audio tokenizer required by MOSS-TTS",
        "required_files": [
            "config.json", "model.safetensors.index.json", "model-00001-of-00002.safetensors",
            "model-00002-of-00002.safetensors",
        ],
    },
}
