# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ComfyUI-GeometryPack Contributors

"""
Individual reconstruction backend nodes (hidden from UI, invoked via unified Reconstruct Surface node).
"""

from .poisson import NODE_CLASS_MAPPINGS as POISSON_MAPS, NODE_DISPLAY_NAME_MAPPINGS as POISSON_DISP
from .ball_pivoting import NODE_CLASS_MAPPINGS as BP_MAPS, NODE_DISPLAY_NAME_MAPPINGS as BP_DISP
from .alpha_shape import NODE_CLASS_MAPPINGS as AS_MAPS, NODE_DISPLAY_NAME_MAPPINGS as AS_DISP
from .convex_hull import NODE_CLASS_MAPPINGS as CH_MAPS, NODE_DISPLAY_NAME_MAPPINGS as CH_DISP
NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(POISSON_MAPS)
NODE_CLASS_MAPPINGS.update(BP_MAPS)
NODE_CLASS_MAPPINGS.update(AS_MAPS)
NODE_CLASS_MAPPINGS.update(CH_MAPS)

NODE_DISPLAY_NAME_MAPPINGS.update(POISSON_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(BP_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(AS_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(CH_DISP)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
