"""Static asset & SPA serving for the mobile UI.

Split out of ``__init__.py``. The SPA catch-all shadows every route
registered after it, so ``register_routes`` must be called **last** in
``setup_mobile_route``.
"""

import mimetypes
import os
from aiohttp import web

from mobile_common import DIST_DIR

# Handler to serve index.html for SPA routing (non-API routes only)
async def serve_index(request):
    # Don't serve index.html for API routes. request.path is the full path
    # (e.g. "/mobile/api/..."), so match "/api/" anywhere rather than only at
    # the start — otherwise an unregistered API route falls through to the SPA
    # and returns HTML with a 200, which breaks JSON clients/health probes.
    path = request.path
    if '/api/' in path:
        return web.Response(status=404, text='Not found')
    response = web.FileResponse(os.path.join(DIST_DIR, "index.html"))
    response.headers['Cache-Control'] = 'no-cache'
    return response

# Serve static assets (must be before catch-all).
#
# We don't use web.static here because we want two things ComfyUI's defaults
# work against: (1) serve a precompressed .br/.gz sibling when the client
# accepts it — Vite emits a single ~1 MB JS chunk and brotli takes it to
# ~250 KB on the wire (siblings are generated by scripts/compress-assets.mjs
# at build time); (2) cache aggressively — asset filenames are content-hashed
# by Vite, so a new build always yields a new URL, making the bytes safely
# immutable. ComfyUI's cache middleware stamps `no-cache` on .js/.css via
# setdefault(), so we must set Cache-Control explicitly here to win.
ASSETS_DIR = os.path.realpath(os.path.join(DIST_DIR, 'assets'))

async def serve_asset(request):
    rel = request.match_info.get('path', '')
    full = os.path.realpath(os.path.join(ASSETS_DIR, rel))
    # Reject path traversal outside the assets dir.
    if full != ASSETS_DIR and not full.startswith(ASSETS_DIR + os.sep):
        return web.Response(status=403, text='Forbidden')
    if not os.path.isfile(full):
        return web.Response(status=404, text='Not found')

    # Vary on every response (compressed and uncompressed) so a shared cache
    # never hands an identity-encoded body to a br/gzip client or vice versa.
    headers = {
        'Cache-Control': 'public, max-age=31536000, immutable',
        'Vary': 'Accept-Encoding',
    }
    content_type = mimetypes.guess_type(full)[0] or 'application/octet-stream'
    accept_encoding = request.headers.get('Accept-Encoding', '')

    # Prefer brotli, then gzip, falling back to the raw file. Content-Type is
    # forced from the ORIGINAL filename so the .br/.gz extension doesn't make
    # aiohttp report application/gzip etc.
    for encoding, suffix in (('br', '.br'), ('gzip', '.gz')):
        if encoding in accept_encoding and os.path.isfile(full + suffix):
            response = web.FileResponse(full + suffix, headers=headers)
            response.content_type = content_type
            response.headers['Content-Encoding'] = encoding
            return response

    return web.FileResponse(full, headers=headers)


# Serve specific root-level static files that Vite emits to the dist root
# (PWA manifest, service worker, icons). These need explicit routes: the SPA
# catch-all below would otherwise return index.html for them. The service
# worker MUST be served from /mobile/ (not /mobile/assets/) so its scope can
# cover the whole app, and with no-cache so updates are picked up.
_ROOT_STATIC_FILES = {
    'sw.js': ('application/javascript', 'no-cache'),
    'manifest.webmanifest': ('application/manifest+json', 'no-cache'),
    'vite.svg': ('image/svg+xml', 'public, max-age=86400'),
    'icon-192.png': ('image/png', 'public, max-age=86400'),
    'icon-512.png': ('image/png', 'public, max-age=86400'),
    'icon-180.png': ('image/png', 'public, max-age=86400'),
    'icon-maskable-512.png': ('image/png', 'public, max-age=86400'),
}

async def serve_root_static(request):
    name = os.path.basename(request.path)
    meta = _ROOT_STATIC_FILES.get(name)
    if meta is None:
        return web.Response(status=404, text='Not found')
    full = os.path.join(DIST_DIR, name)
    if not os.path.isfile(full):
        return web.Response(status=404, text='Not found')
    content_type, cache_control = meta
    headers = {'Cache-Control': cache_control}
    if name == 'sw.js':
        headers['Service-Worker-Allowed'] = '/mobile/'
    response = web.FileResponse(full, headers=headers)
    response.content_type = content_type
    return response


def register_routes(mobile_app):
    """Register static/SPA routes. Must run after all other route groups."""
    mobile_app.router.add_get('/assets/{path:.*}', serve_asset)
    for _name in _ROOT_STATIC_FILES:
        mobile_app.router.add_get('/' + _name, serve_root_static)

    # Serve index.html for root and all non-API routes (SPA)
    mobile_app.router.add_get('/', serve_index)
    mobile_app.router.add_get('/{path:.*}', serve_index)
