[dependencies]
av = "*"

[cuda]
packages = ["cumesh"]

[pypi-dependencies]
numpy = "*"
trimesh = { version = ">=4.0.0", extras = ["easy"] }
tqdm = "*"
psutil = "*"
safetensors = "*"
comfy-aimdo = "*"
einops = "*"

[target.win-64.pypi-dependencies]
msvc-runtime = "*"

[env_vars]
KMP_DUPLICATE_LIB_OK = "TRUE"
