import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const source = await readFile(new URL("../js/minimax_h3_director_v2.js", import.meta.url), "utf8");
assert.match(source, /seed_control/, "seed-control state must persist with the Director workflow");
assert.match(source, /Random/, "seed control must offer Random mode");
assert.match(source, /Fixed/, "seed control must offer Fixed mode");
assert.match(source, /retain the selected mode/, "seed control must roll without changing the selected mode");
assert.match(source, /Use Last/, "seed control must restore the last generated seed");
assert.match(source, /Last 10 seeds/, "seed control must expose the last ten seeds");
assert.match(source, /textContent = "SEED"/, "seed control must use the same uppercase heading convention as aspect");
assert.match(source, /seedControl\.append\(seedField, toggle/, "seed controls must start with their left-aligned heading");
assert.match(source, /Copy seed/, "each recent seed must expose a copy action");
assert.match(source, /textContent = "Use Last"/, "the reuse action must stay compact");
assert.match(source, /ds-h3-res-switch-seg\{flex:1;min-width:56px/, "Random and Fixed must be one segmented switch with equal segments");
assert.match(source, /ds-h3-res-spinbtn/, "the seed number field must carry an attached up/down spinner");
assert.match(source, /lastSeedText/, "the seed panel must keep a lossless decimal string as the source of truth");
assert.match(source, /writeSeedMirror/, "the native number widget must be written as a mirror, never read back");
assert.match(source, /stepSeed/, "the spinner must step the seed in place via BigInt with 64-bit wrap");
assert.match(source, /fitSeedFont/, "the seed field must shrink its font so full 64-bit digits stay visible");
assert.match(source, /width:68px/, "New and Use Last controls must have equal widths");
assert.match(source, /addWidget\("number", "seed"/, "the Director needs a hidden local seed widget when its external socket is not wired");
assert.match(source, /align-items:flex-end/, "seed action controls must share a horizontal baseline");
assert.match(source, /textAlign = "center"/, "seed control labels must be centered");
assert.match(source, /if \(onSettings\)/, "optimization pills must only render a settings burger when settings exist");
assert.match(source, /makeOptPill\("Comfy Kitchen Attention"[^\n]*, null\)/, "Comfy Kitchen Attention must not receive a settings menu");
assert.doesNotMatch(source, /toggle\.style\.cssText = "display:flex;gap:2px;padding-bottom:2px"/, "Random and Fixed must not be vertically offset");
assert.doesNotMatch(source, /history\.style\.cssText = "position:relative;padding-bottom:2px"/, "Last 10 must not be vertically offset");
assert.match(source, /text-align:center/, "seed action labels must be centered in their buttons");
assert.doesNotMatch(source, /state\.textContent = active \? "on" : "off"/, "optimization pills must not render redundant on/off labels");
assert.doesNotMatch(source, /remember\(value\); controlState\.mode = "fixed"/, "New must preserve the selected Random or Fixed mode");
assert.match(source, /remember\(value\); emit\(\); syncSwitch\(\);/, "New must remember its rolled seed and update the switch in place");
assert.match(source, /justify-content:center/, "seed controls must center flex button contents");
assert.match(source, /seedField\.style\.cssText = "display:flex;flex-direction:column;gap:3px;min-width:168px;font-size:10px;font-weight:600;letter-spacing:\.4px;color:#8fb3d6;text-transform:uppercase"/, "SEED must use the same label style as ASPECT");
assert.match(source, /field\.style\.cssText = "display:flex;flex-direction:row;align-items:center;gap:6px;margin:7px 0;font-size:11px"/, "boolean stage settings must render as one checkbox-first row");
assert.match(source, /field\.append\(input, title\)/, "boolean stage setting checkbox must appear before its option label");
assert.match(source, /saveTitle\.textContent = "Preview & Output"/, "save panel must use the Preview & Output title");
assert.match(source, /saveHint\.textContent/, "save panel must show selected output settings");
assert.match(source, /color:#7ee19d/, "selected output settings must be a green hint");
assert.match(source, /file_format: "webp", compression: 15/, "new Director image outputs must default to WebP compression 15");
assert.match(source, /\{ key: "file_format", type: "combo", options: \["webp", "png"\], default: "webp" \}/, "the save settings modal must default to WebP");
assert.match(source, /filename_prefix/, "output hint must include the selected filename prefix");
assert.match(source, /pingpong/, "output hint must include selected ping-pong state");
assert.match(source, /crop_to_audio/, "output hint must include selected crop-to-audio state");
assert.match(source, /save_first_frame/, "output hint must include selected frame-export state");
assert.match(source, /save_workflow/, "output hint must include selected workflow embedding state");
assert.match(source, /ds-h3-info-feed/, "Director must render a dedicated information feed before media inputs");
assert.match(source, /grid-template-columns:minmax\(0,1fr\) minmax\(0,1\.2fr\)/, "Preview & Output must receive more width than controls");
assert.match(source, /min-height:420px/, "Preview & Output must be substantially taller");
assert.match(source, /contentLayout\.append\(leftColumn, saveNodePanel\)/, "all controls, media inputs, and prompt content must be in the left column beside Preview & Output");
assert.match(source, /leftColumn\.append\(controlRow, infoFeed, track, promptPanel\)/, "left column must contain Director controls, feed, media inputs, and prompts");
assert.match(source, /align-items:stretch/, "Preview & Output must stretch to the full authoring-column height");
assert.match(source, /height:100%/, "Preview & Output panel must fill its stretched grid cell");
assert.match(source, /infoFeed\.append\(readout, postprocessInfo\)/, "resolution and post-processing summary must share the information feed");
assert.match(source, /modeGroup\.append\(resolutionPanel, postprocessPanel, optimizationPanel\)/, "post-processing and optimization controls must remain with the other controls");
assert.match(source, /ds-h3-info-feed[^\n]*background:#0d1217[^\n]*border:1px solid #344452[^\n]*border-radius:6px/, "information feed must use the same framed background treatment as controls");
assert.match(source, /ppSummary\.style\.cssText = "width:100%;box-sizing:border-box;text-align:left/, "post-processing summary must align left with the resolution readout");
assert.match(source, /saveHeader\.append\(saveTitle, saveMenu\)/, "Preview & Output must place its burger beside the headline");
assert.match(source, /saveMenu\.textContent = "☰"/, "save options must use a burger button instead of a gear");
assert.match(source, /save_output/, "save options menu must retain Save output setting");
assert.match(source, /save_workflow/, "save options menu must retain Embed workflow setting");
assert.match(source, /MiniMaxH3DirectorV2/, "Director frontend must install for the new 2.0 node class");
assert.match(source, /BigInt/, "seed values must retain the full unsigned 64-bit range");
// ---- Workstream A: sampling panel + external sampling override sockets ----
assert.ok(source.includes("const SAMPLER_OPTIONS = ["), "Director must define the MiniMax H3 sampler option list");
assert.ok(source.includes("const SCHEDULER_OPTIONS = ["), "Director must define the MiniMax H3 scheduler option list");
assert.ok(source.includes("res_multistep"), "the default MiniMax H3 sampler must be available");
assert.ok(source.includes("updateExec = (patch)"), "sampling edits must write through updateExec into internal_execution");
assert.ok(source.includes("s.internal_execution = next"), "updateExec must target state.internal_execution so sampling persists");
assert.ok(source.includes("Math.max(1, Math.min(1000, Math.trunc(next.steps || 25)))"), "steps must clamp to 1..1000 with a 25 fallback");
assert.ok(source.includes("Math.max(0, Number(next.shift_video) || 0)"), "shift_video must clamp to >= 0");
assert.ok(source.includes("Math.max(0, Number(next.shift_audio) || 0)"), "shift_audio must clamp to >= 0");
assert.ok(source.includes("hasExternalSampling = ()"), "Director must detect linked external sampling sockets");
for (const socket of ["external_sampler", "external_scheduler", "external_steps", "external_shift_video", "external_shift_audio"]) {
  assert.ok(source.includes(socket), `external sampling socket ${socket} must be checked`);
}
assert.ok(source.includes("External sampling connected"), "a linked sampling socket must disable the local fields with a note");
assert.ok(source.includes('samplingPanel.querySelectorAll("select, input, button")'), "external sampling must disable the sampling controls");
assert.ok(source.includes("const externalSamplingLinked = hasExternalSampling();"), "connection/poll changes must re-evaluate external sampling");
// ---- Workstream B: built-in live step preview ----
assert.ok(source.includes("PREVIEW_OPTION_FIELDS = ["), "Director must define the preview & output option fields");
assert.ok(source.includes("live_step_preview"), "preview options must include the live step preview toggle");
assert.ok(source.includes("preview_max_resolution"), "preview options must include a max resolution setting");
assert.ok(source.includes("preview_frames"), "preview options must include a frame-count setting");
assert.ok(source.includes("preview_fps"), "preview options must include a frame-rate setting");
assert.ok(source.includes("...PREVIEW_OPTION_FIELDS"), "preview options must render inside the Preview & Output options menu");
assert.ok(source.includes('api.addEventListener("dasiwa_director_v2_preview"'), "the live step-preview pane must subscribe to the backend preview event");
assert.ok(source.includes("__dasiwaH3ShowStepPreview"), "preview events must route to the matching node's live slot");
assert.ok(source.includes("step ${payload.step}/"), "the live slot must caption the current step over the total");
// ---- Preview popup width ----
assert.match(source, /\.ds-h3-preview-panel\{width:min\(400px,90vw\)/, "the media preview popup must be a third narrower (400px, was 600px)");
// ---- preview_tiny_vae combo ring strip ----
assert.match(source, /input\.name === "preview_tiny_vae"/, "the Director must target the preview_tiny_vae socket to strip its ring");
assert.match(source, /input\.shape = null/, "the preview_tiny_vae optional socket shape must be nulled so no hollow ring draws (VAELoader look)");
assert.match(source, /for \(const input of node\.inputs \|\| \[\]\)/, "the ring strip must iterate the node's input sockets");
