[dependencies]
av = "*"
numpy = "*"
safetensors = "*"
einops = "*"
psutil = "*"
tqdm = "*"

[cuda]
packages = ["cumesh"]

[pypi-dependencies]
trimesh = { version = ">=4.0.0", extras = ["easy"] }
comfy-aimdo = "*"

[target.win-64.pypi-dependencies]
msvc-runtime = "*"

[env_vars]
KMP_DUPLICATE_LIB_OK = "TRUE"
