from .star_minimax_aio import NODE_CLASS_MAPPINGS as STAR_MINIMAX_AIO_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_MINIMAX_AIO_NODE_DISPLAY_NAMES

NODE_CLASS_MAPPINGS = {
    **STAR_MINIMAX_AIO_NODE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **STAR_MINIMAX_AIO_NODE_DISPLAY_NAMES,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
