from .AILab_SparkTTS import NODE_CLASS_MAPPINGS as SPARK_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SPARK_NODE_DISPLAY_NAME_MAPPINGS
from .AILab_AudioRecorder import NODE_CLASS_MAPPINGS as AUDIO_RECORDER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as AUDIO_RECORDER_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**SPARK_NODE_CLASS_MAPPINGS, **AUDIO_RECORDER_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**SPARK_NODE_DISPLAY_NAME_MAPPINGS, **AUDIO_RECORDER_NODE_DISPLAY_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']