[project]
name = "ComfyUI_RaykoStudio"
description = "Set of custom nodes for ComfyUI providing additional image processing capabilities"
version = "0.33.0"
license = { file = "LICENSE" }
dependencies = ["torch", "numpy", "Pillow>=10.0.0", "freetype-py>=2.5.1", "pycairo>=1.29.0", "scipy>=1.10.0"]

[project.urls]
Repository = "https://github.com/Raykosan/ComfyUI_RaykoStudio"

[tool.comfy]
PublisherId = "raykosan"
DisplayName = "ComfyUI_RaykoStudio"
Icon = "https://raw.githubusercontent.com/Raykosan/ComfyUI_RaykoStudio/main/icon.png"
