"""Operator to render from the camera view using custom compositors."""
import logging
import os
import shutil

import bpy

from ..utils import get_inputs_folder, get_temp_folder, upload_file

log = logging.getLogger("comfyui_blender")


class ComfyBlenderOperatorRenderDepthMap(bpy.types.Operator):
    """Operator to render from the camera view using custom compositors."""

    bl_idname = "comfy.render_custom_compositor"
    bl_label = "Render Using Custom Compositor"
    bl_description = "Render from the camera using custom compositors and upload the image to the ComfyUI server."

    compositor_name: bpy.props.StringProperty(name="Compositor Name")
    workflow_property: bpy.props.StringProperty(name="Workflow Property")

    def reset_scene(self, context, **kwargs):
        """Reset the scene to its initial state."""

        # Restore original render settings
        scene = context.scene
        scene.render.filepath = kwargs["original_filepath"]

        # Remove temporary files
        if os.path.exists(kwargs["extra_filepath"]):
            os.remove(kwargs["extra_filepath"])
        if os.path.exists(kwargs["temp_filepath"]):
            os.remove(kwargs["temp_filepath"])

    def execute(self, context):
        """Execute the operator."""

        scene = context.scene
        if not scene.camera:
            error_message = "No camera found"
            log.error(error_message)
            bpy.ops.comfy.show_error_popup("INVOKE_DEFAULT", error_message=error_message)
            return {'CANCELLED'}

        # Build temp file paths
        temp_folder = get_temp_folder()
        extra_filepath = os.path.join(temp_folder, "tmp.png")  # Extraneous file generated by Blender renderer

        # Initialize scene reset settings
        reset_params = {}
        reset_params["extra_filepath"] = extra_filepath
        reset_params["original_filepath"] = scene.render.filepath

        # Set up the scene for rendering
        scene.render.filepath = extra_filepath

        # Get the file output node
        tree = bpy.data.node_groups[self.compositor_name]
        output_file_nodes = [node for node in tree.nodes if node.type == "OUTPUT_FILE"]
        if output_file_nodes:
            if len(output_file_nodes) > 1:
                error_message = f"Compositor '{self.compositor_name}' has more than one File Output node. Modify the compositor to have only one File Output node."
                log.error(error_message)
                bpy.ops.comfy.show_error_popup("INVOKE_DEFAULT", error_message=error_message)
                return {'CANCELLED'}

            # Check the file output node property media type
            output_file_node = output_file_nodes[0]
            media_type = output_file_node.format.media_type
            if media_type != "IMAGE":
                error_message = f"The media type '{media_type}' of the File Output node is not supported. Modify the File Output node to set the media type to 'IMAGE'."
                log.error(error_message)
                bpy.ops.comfy.show_error_popup("INVOKE_DEFAULT", error_message=error_message)
                return {'CANCELLED'}

            # Check the file output node property file format
            file_format = output_file_node.format.file_format
            if file_format == "PNG":
                extension = ".png"
            elif file_format == "JPEG":
                extension = ".jpg"
            elif file_format == "WEBP":
                extension = ".webp"
            else:
                error_message = f"The file format '{file_format}' of the File Output node is not supported. Modify the File Output node to set the format to 'PNG', 'JPEG' or 'WEBP'."
                log.error(error_message)
                bpy.ops.comfy.show_error_popup("INVOKE_DEFAULT", error_message=error_message)
                return {'CANCELLED'}
    
            # Check the file output node property file output items
            file_output_items = output_file_node.file_output_items
            if file_output_items:
                if len(file_output_items) > 1:
                    outputs = ", ".join([item.name for item in file_output_items])
                    error_message = f"The File Output node has more than one output: {outputs}. Modify the File Output node to set a single output."
                    log.error(error_message)
                    bpy.ops.comfy.show_error_popup("INVOKE_DEFAULT", error_message=error_message)
                    return {'CANCELLED'}
            else:
                error_message = f"The File Output node does not have an image output. Modify the File Output node to set a single output."
                log.error(error_message)
                bpy.ops.comfy.show_error_popup("INVOKE_DEFAULT", error_message=error_message)
                return {'CANCELLED'}

        else:
            error_message = f"Compositor '{self.compositor_name}' does not have a File Output node. Modify the compositor to add a File Output node."
            log.error(error_message)
            bpy.ops.comfy.show_error_popup("INVOKE_DEFAULT", error_message=error_message)
            return {'CANCELLED'}

        # Render the scene
        output_file_node.directory = temp_folder
        scene.compositing_node_group = tree
        bpy.ops.render.render(write_still=True)

        # Get the rendered file path
        temp_filename = output_file_node.file_name + file_output_items[0].name + extension
        temp_filepath = os.path.join(temp_folder, temp_filename)
        reset_params["temp_filepath"] = temp_filepath  # Add the temp filepath to the reset param to delete it later

        # Upload file on ComfyUI server
        try:
            response = upload_file(temp_filepath, type="image")
        except Exception as e:
            # Reset the scene to initial state
            # self.reset_scene(context, **reset_params)
            addon_prefs = context.preferences.addons["comfyui_blender"].preferences
            error_message = f"Failed to upload file to ComfyUI server: {addon_prefs.server_address}. {e}"
            log.exception(error_message)
            bpy.ops.comfy.show_error_popup("INVOKE_DEFAULT", error_message=error_message)
            return {'CANCELLED'}

        if response.status_code != 200:
            # Reset the scene to initial state
            # self.reset_scene(context, **reset_params)
            error_message = f"Failed to upload file: {response.status_code} - {response.text}"
            log.error(error_message)
            bpy.ops.comfy.show_error_popup("INVOKE_DEFAULT", error_message=error_message)
            return {'CANCELLED'}

        # Delete the previous input image from Blender's data
        current_workflow = scene.current_workflow
        previous_image = getattr(current_workflow, self.workflow_property)
        if previous_image:
            bpy.data.images.remove(previous_image)

        # Build input file paths
        inputs_folder = get_inputs_folder()
        input_subfolder = response.json()["subfolder"]
        input_filename = response.json()["name"]
        input_filepath = os.path.join(inputs_folder, input_subfolder, input_filename)

        # Create the input subfolder if it doesn't exist
        os.makedirs(os.path.join(inputs_folder, input_subfolder), exist_ok=True)

        try:
            # Copy the file to the inputs folder
            shutil.copy(temp_filepath, input_filepath)
            self.report({'INFO'}, f"Input file copied to: {input_filepath}")
        except shutil.SameFileError as e:
            self.report({'INFO'}, f"Input file is already in the inputs folder: {input_filepath}")
        except Exception as e:
            # Reset the scene to initial state
            # self.reset_scene(context, **reset_params)
            error_message = f"Failed to copy input file: {e}"
            log.exception(error_message)
            bpy.ops.comfy.show_error_popup("INVOKE_DEFAULT", error_message=error_message)
            return {'CANCELLED'}

        # Load image in the data block
        image = bpy.data.images.load(input_filepath, check_existing=True)

        # Update the workflow property with the image from the data block
        setattr(current_workflow, self.workflow_property, image)

        # Reset the scene to initial state
        # self.reset_scene(context, **reset_params)
        return {'FINISHED'}


def register():
    """Register the operator."""

    bpy.utils.register_class(ComfyBlenderOperatorRenderDepthMap)


def unregister():
    """Unregister the operator."""

    bpy.utils.unregister_class(ComfyBlenderOperatorRenderDepthMap)
