"""
ComfyUI nodes for Maya1 TTS.
"""

from .maya1_tts_combined import (
    Maya1TTSCombinedNode,
    NODE_CLASS_MAPPINGS as COMBINED_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as COMBINED_DISPLAY_MAPPINGS
)

from .maya1_tts_barebones import (
    Maya1TTSBarebonesNode,
    NODE_CLASS_MAPPINGS as BAREBONES_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BAREBONES_DISPLAY_MAPPINGS
)

# Merge the mappings from both nodes
NODE_CLASS_MAPPINGS = {**COMBINED_MAPPINGS, **BAREBONES_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**COMBINED_DISPLAY_MAPPINGS, **BAREBONES_DISPLAY_MAPPINGS}

__all__ = [
    "Maya1TTSCombinedNode",
    "Maya1TTSBarebonesNode",
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]
