from .pipeline_cogvideox_fun import CogVideoXFunPipeline
from .pipeline_cogvideox_fun_control import CogVideoXFunControlPipeline
from .pipeline_cogvideox_fun_inpaint import CogVideoXFunInpaintPipeline
from .pipeline_ernie_image import ErnieImagePipeline
from .pipeline_fantasytalking import FantasyTalkingPipeline
from .pipeline_flashhead import FlashHeadPipeline
from .pipeline_flux import FluxPipeline
from .pipeline_flux2 import Flux2Pipeline
from .pipeline_flux2_control import Flux2ControlPipeline
from .pipeline_hunyuanvideo import HunyuanVideoPipeline
from .pipeline_hunyuanvideo_i2v import HunyuanVideoI2VPipeline
from .pipeline_infinitetalk import InfiniteTalkPipeline
from .pipeline_longcatvideo import LongCatVideoPipeline
from .pipeline_longcatvideo_avatar import LongCatVideoAvatarPipeline
from .pipeline_ltx2 import LTX2Pipeline
from .pipeline_ltx2_i2v import LTX2I2VPipeline
from .pipeline_ltx2_latent_upsample import LTX2LatentUpsamplePipeline
from .pipeline_lens import LensPipeline
from .pipeline_mova import MOVAPipeline
from .pipeline_qwenimage import QwenImagePipeline
from .pipeline_qwenimage_control import QwenImageControlPipeline
from .pipeline_qwenimage_edit import QwenImageEditPipeline
from .pipeline_qwenimage_edit_plus import QwenImageEditPlusPipeline
from .pipeline_qwenimage_instantx import QwenImageControlNetPipeline
from .pipeline_qwenimage_layered import QwenImageLayeredPipeline
from .pipeline_wan import WanPipeline
from .pipeline_wan2_2 import Wan2_2Pipeline
from .pipeline_wan2_2_animate import Wan2_2AnimatePipeline
from .pipeline_wan2_2_fun_control import Wan2_2FunControlPipeline
from .pipeline_wan2_2_fun_inpaint import Wan2_2FunInpaintPipeline
from .pipeline_wan2_2_s2v import Wan2_2S2VPipeline
from .pipeline_wan2_2_ti2v import Wan2_2TI2VPipeline
from .pipeline_wan2_2_vace_fun import Wan2_2VaceFunPipeline
from .pipeline_wan_fun_control import WanFunControlPipeline
from .pipeline_wan_fun_inpaint import WanFunInpaintPipeline
from .pipeline_wan_phantom import WanFunPhantomPipeline
from .pipeline_wan_self_forcing import WanSelfForcingPipeline
from .pipeline_wan_vace import WanVacePipeline
from .pipeline_z_image import ZImagePipeline
from .pipeline_z_image_control import ZImageControlPipeline

WanFunPipeline = WanPipeline
WanI2VPipeline = WanFunInpaintPipeline

Wan2_2FunPipeline = Wan2_2Pipeline
Wan2_2I2VPipeline = Wan2_2FunInpaintPipeline