// Editable authoring examples, not generation settings or runtime overrides.
// Format: https://huggingface.co/MiniMaxAI/MiniMax-H3/blob/main/docs/VIDEO_PROMPT_WRITING_GUIDE_ref_en.md
export const H3_REFERENCE_DEMOS = [
    {
        id: "demo_v2v_style", label: "DEMO · V2V / clay-animation restyle", name: "R37B · V2V Clay Animation",
        mode: "ref2va", shotboardMode: "v2va_object_swap", video: true, picture: false,
        request: "Restyle the supplied five-second forest-performer video as handcrafted clay animation. Keep its performer, gestures, composition and camera timing. Generate quiet forest ambience; do not reuse the source soundtrack.",
        hint: "Connect the source clip to Cine Info H3 → reference_video, select video_edit there, and select V2VA in H3 Settings. Use 24 fps. No picture or audio reference is needed. This is semantic video editing, not a pixel-locked transformation.",
        sections: {
            subject_definitions: "<Subject 1> is the single green-skinned forest goblin in <Video 1>, with long pointed ears, a yellow flower crown, a dark wet coat and a raised hand.\n<Subject 2> is the flooded woodland in <Video 1>, with thin tree trunks, pale mist and reflective shallow water.\n<Video 1> is the source video being edited; its visual track defines the action order, shot composition and camera movement.",
            summary: "[video editing] The target video is an edited version of <Video 1>. Convert its live-action fantasy appearance into handcrafted clay animation while retaining <Subject 1>, <Subject 2>, the original gesture sequence and the source camera design. Generate a new, quiet environmental soundtrack without dialogue.",
            retention_analysis: "<Subject 1> (appears in [Shot 1]): partially_preserved - keep the recognizable silhouette, green complexion, pointed ears, flower crown, dark coat and gesture order; change skin, fabric and flowers to visibly modeled clay and miniature materials.\n<Subject 2> (appears in [Shot 1]): partially_preserved - retain tree positions, waterline, mist depth and lighting direction; render them as a miniature woodland set.\n<Video 1> (whole visual sequence): partially_preserved - preserve the framing, camera path, action rhythm and occlusion order; change only the image-making style. The source soundtrack is not supplied as an audio reference.",
            detailed_description: "The target video has a tactile, handcrafted clay-animation finish, photographed as a convincing miniature set with soft cinematic light. [Shot 1] Open on the same composition as <Video 1>: <Subject 1>, the flower-crowned goblin in the dark coat, stands in the shallow reflective water of <Subject 2>. Reproduce the source's successive head turns, eye direction, reaching hand and changes of posture in their original order. Follow the actual source motion rather than inventing a different performance or moving the character to a new screen position. The green face is sculpted clay with delicate tool marks; the flower petals and coat folds retain a consistent material scale throughout the shot. Preserve the goblin's identity and the anatomy of its reaching hand.\nKeep the source camera trajectory and framing progression. Tree trunks remain attached to their original locations, their reflections follow the water surface, and mist stays behind the performer. Light continues to arrive from the same direction as in the source. The clay finish remains stable on both face and background during movement, with no alternating live-action frames or sudden texture changes. End at the same stage of the visible action as the supplied clip. Maintain a single full-frame scene, without a new cut, title, border, caption or logo. Generate only gentle water movement, a light woodland breeze and subtle wet-cloth movement; do not invent speech to accompany the mouth motion.",
            overall_soundscape: "Newly generated quiet woodland air, soft ripples and restrained cloth movement, following the visible action. No copied source audio, intelligible dialogue or added narrator.",
            non_diegetic_music: "N/A",
        },
    },
    {
        id: "demo_v2v_character", label: "DEMO · V2V / replace with sheet character", name: "R37B · V2V Character Replacement",
        mode: "ref2va", shotboardMode: "v2va_object_swap", video: true, picture: true,
        request: "Replace the goblin in the source video with the young man from the bottom panel of COMPO.PNG. Keep the flooded forest, camera, gestures and timing. Ignore the woman and ice landscape in this particular edit.",
        hint: "Video 1 = source clip. Picture 1 = complete COMPO sheet. Only its bottom male-character panel is used in this preset. Connect both outside the Shotboard; keep a text-only timeline slot. Video edit is a reference-conditioned reconstruction, not a guaranteed face swap.",
        sections: {
            subject_definitions: "<Subject 1> is the young adult man in the bottom panel of <Picture 1>, with curly brown hair, a clean-shaven face, a dark navy long coat with gold embroidery, a gold waistcoat, a white lace cravat and tall black boots. The portrait and turnaround views in that panel depict this one man.\n<Subject 2> is the flower-crowned green goblin being replaced in <Video 1>.\n<Subject 3> is the flooded forest in <Video 1>, including its shallow water, thin tree trunks, pale mist and lighting.\n<Video 1> is the source video for the character-replacement edit.",
            summary: "[video editing + reference generation] The target video is an edited version of <Video 1>. Replace <Subject 2> with <Subject 1> while retaining the source's gestures, screen position, shot composition and camera timing inside <Subject 3>. Generate quiet environmental audio, without dialogue or copied source sound.",
            retention_analysis: "<Subject 1> (appears in [Shot 1]): fully_preserved - take only the male identity, curly hair, navy-and-gold costume, cravat and body proportions from the bottom panel of <Picture 1>; naturally wet the lower coat where it touches water.\n<Subject 2> (replacement target in [Shot 1]): attribute_transfer - transfer its visible pose sequence, gesture timing, gaze changes and position to <Subject 1>, but not its face, green skin, pointed ears, flower crown or old costume.\n<Subject 3> (appears in [Shot 1]): fully_preserved - keep the source woodland, waterline, mist, light direction and spatial relationships.\n<Video 1> (whole visual sequence): partially_preserved - preserve action chronology, framing and camera path while replacing only the principal performer. Ignore the woman and glacial landscape in <Picture 1> for this edit.",
            detailed_description: "Photorealistic cinematic fantasy with the source video's soft misty light and restrained contrast. [Shot 1] Begin at the same camera position and shot scale as <Video 1>. <Subject 1>, the curly-haired man from the bottom panel of <Picture 1>, occupies the exact narrative role and screen region previously occupied by <Subject 2>. His human face, navy coat, gold embroidery and white cravat are already fully established in the opening frame. He is the only visible performer. His lower body stands at the source waterline, with plausible contact, damp fabric and a reflection tied to his new silhouette.\nFollow the supplied clip's successive hand gestures, head motion and body shifts in their original order and relative timing. Preserve which hand is raised and which parts of the body pass in front of the coat or face. Adapt the gestures naturally to the man's human proportions without retaining goblin anatomy. Keep the source camera movement, framing changes and depth relationships. The surrounding flooded trees and drifting mist remain <Subject 3>; do not transplant the iceberg landscape or introduce the red-dressed woman from the other panels.\nMaintain the same male identity throughout the movement and finish at the source clip's final action state. There is no on-screen transformation, dissolve from goblin to man, costume swap, duplicate performer or return to the original face. The sheet is an identity reference, never the opening composition: no collage layout, white studio backdrop, panel border, repeated turnaround views or printed text appears in the film. Use subtle water and clothing sounds only, without generating a new spoken line.",
            overall_soundscape: "Newly generated low woodland ambience and small water contacts corresponding to the retained movement. No source soundtrack, narrator or intelligible speech.",
            non_diegetic_music: "N/A",
        },
    },
    {
        id: "demo_composite_sheet", label: "DEMO · one sheet / two people + environment", name: "R37B · COMPO Two Characters on Ice",
        mode: "ref2va", shotboardMode: "ref2va", video: false, picture: true,
        request: "Use COMPO.PNG as one reference containing two character turnarounds and an environment. Put the woman in red and the man in navy and gold together beside the icy lagoon. Make one cinematic shot, not an animated collage, with two brief alternating lines.",
        hint: "Load COMPO.PNG once into Cine Info H3 → reference_image_1. Top right = one woman; bottom = one man; top left = environment. All three are Subjects from Picture 1, not Pictures 1–3. Use REF2VA and generated H3 audio. Leave Shotboard images empty; its text slot owns duration and direction.",
        sections: {
            subject_definitions: "<Subject 1> is the adult woman in the top-right panel of <Picture 1>, with auburn finger-wave hair, red lipstick, a fitted glossy red dress with puffed shoulders, a dark belt, a gold necklace and red heels. The close-up and front, side and rear views are the same woman, not separate people.\n<Subject 2> is the young adult man in the bottom panel of <Picture 1>, with curly brown hair, a clean-shaven face, a navy long coat with gold embroidery, a gold waistcoat, a white lace cravat and tall black boots. The portrait and turnaround views are the same man.\n<Subject 3> is the glacial lagoon in the top-left panel of <Picture 1>, with blue ice cliffs, scattered floating ice, reflective water, distant dark mountains and warm low sunlight breaking through clouds.",
            summary: "[reference generation] In one cinematic shot, <Subject 1> and <Subject 2> stand together on a stable icy shore overlooking <Subject 3>. A faint ice crack draws their attention; she speaks briefly and he answers. Assemble a single coherent scene from the reference sheet's two people and environment, not a moving sheet or a sequence of panels.",
            retention_analysis: "<Subject 1> (appears in [Shot 1]): fully_preserved - retain her facial identity, auburn hairstyle, red dress design, belt, necklace and adult proportions from the top-right panel.\n<Subject 2> (appears in [Shot 1]): fully_preserved - retain his facial identity, curly hair, navy-and-gold coat, waistcoat and white cravat from the bottom panel.\n<Subject 3> (appears in [Shot 1]): fully_preserved - retain the blue ice, reflective lagoon, distant mountains and warm-cloud lighting character from the top-left panel. Build a plausible shared camera view; do not preserve the sheet's panel geometry or white backgrounds.",
            detailed_description: "The target video is a photorealistic cinematic fantasy scene with natural skin detail, cool glacial reflections and warm low sunlight. [Shot 1] Open directly on one full-frame medium two-shot beside <Subject 3>, the blue glacial lagoon from the top-left panel of <Picture 1>. <Subject 1>, the auburn-haired woman in the glossy red dress from the top-right panel, stands on screen left. <Subject 2>, the curly-haired man in the navy coat with gold embroidery and white lace cravat from the bottom panel, stands on screen right, half a step behind her. Both are already present as single, solid people in the same physical space. Their feet rest on firm shore rather than floating water. Keep their faces unobstructed, in three-quarter view, and large enough to read their expressions.\nThe pale turquoise ice wall stretches behind them, with scattered ice floating farther out and dark mountains beneath the cloud break. Warm light rims their hair and shoulders while the lagoon contributes a soft blue fill. The woman's glossy dress and the man's gold embroidery respond to this shared lighting rather than the sheet's studio light. Establish one consistent horizon and a believable difference between foreground shore and distant water.\nA soft crack sounds from the lagoon. <Subject 1> glances toward the ice, takes a short breath, then turns her eyes toward <Subject 2>. In a clear, low adult female voice, <Subject 1> (S1) says, <d>[English] The ice is moving.</d> Her lips articulate the line while the man listens with his mouth closed. After a brief natural pause, <Subject 2> meets her gaze. In a calm, warm young adult male voice, <Subject 2> (S2) replies, <d>[English] Then stay close.</d> The woman now listens silently. He makes one small reassuring movement of his open hand, without crossing in front of either face. They finish together looking toward the lagoon.\nUse one gentle, short dolly-in through the entire exchange, with no cut or sudden reframing. Wind moves a few hair strands and the coat hem, while restrained ripples move around the distant ice. Preserve both faces, their distinct costumes, screen sides and scale throughout. The result contains exactly these two people: the repeated portrait and turnaround views do not become extra actors. Do not reproduce white studio backgrounds, black dividers, panels, contact-sheet layout, captions or logos. The film begins inside the scene, never with a transition out of the sheet.",
            overall_soundscape: "Continuous soft glacial wind, gentle water and one distant ice crack before the exchange. Two distinct on-screen voices are generated by H3 with alternating speech and visible articulation; no supplied audio track or off-screen narrator.",
            non_diegetic_music: "N/A",
        },
    },
];
