# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ComfyUI-GeometryPack Contributors

"""
Individual remeshing backend nodes (hidden from UI, invoked via unified Remesh node).
"""

from .pymeshlab_isotropic import NODE_CLASS_MAPPINGS as PML_MAPS, NODE_DISPLAY_NAME_MAPPINGS as PML_DISP
from .instant_meshes import NODE_CLASS_MAPPINGS as IM_MAPS, NODE_DISPLAY_NAME_MAPPINGS as IM_DISP
from .quadriflow import NODE_CLASS_MAPPINGS as QF_MAPS, NODE_DISPLAY_NAME_MAPPINGS as QF_DISP
from .mmg import NODE_CLASS_MAPPINGS as MMG_MAPS, NODE_DISPLAY_NAME_MAPPINGS as MMG_DISP
from .geogram_smooth import NODE_CLASS_MAPPINGS as GS_MAPS, NODE_DISPLAY_NAME_MAPPINGS as GS_DISP
from .geogram_aniso import NODE_CLASS_MAPPINGS as GA_MAPS, NODE_DISPLAY_NAME_MAPPINGS as GA_DISP
from .pmp_uniform import NODE_CLASS_MAPPINGS as PU_MAPS, NODE_DISPLAY_NAME_MAPPINGS as PU_DISP
from .pmp_adaptive import NODE_CLASS_MAPPINGS as PA_MAPS, NODE_DISPLAY_NAME_MAPPINGS as PA_DISP
from .quadwild import NODE_CLASS_MAPPINGS as QW_MAPS, NODE_DISPLAY_NAME_MAPPINGS as QW_DISP

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(PML_MAPS)
NODE_CLASS_MAPPINGS.update(IM_MAPS)
NODE_CLASS_MAPPINGS.update(QF_MAPS)
NODE_CLASS_MAPPINGS.update(MMG_MAPS)
NODE_CLASS_MAPPINGS.update(GS_MAPS)
NODE_CLASS_MAPPINGS.update(GA_MAPS)
NODE_CLASS_MAPPINGS.update(PU_MAPS)
NODE_CLASS_MAPPINGS.update(PA_MAPS)
NODE_CLASS_MAPPINGS.update(QW_MAPS)

NODE_DISPLAY_NAME_MAPPINGS.update(PML_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(IM_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(QF_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(MMG_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(GS_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(GA_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(PU_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(PA_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(QW_DISP)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
