"""Operator to render from the camera view."""
import logging
import os
import shutil

import bpy

from ..utils import get_inputs_folder, get_temp_folder, upload_file

log = logging.getLogger("comfyui_blender")


class ComfyBlenderOperatorRenderDepthMap(bpy.types.Operator):
    """Operator to render from the camera view."""

    bl_idname = "comfy.render_view"
    bl_label = "Render View"
    bl_description = "Render from the camera and upload it to the ComfyUI server."

    workflow_property: bpy.props.StringProperty(name="Workflow Property")
    temp_filename = "blender_render"

    def reset_scene(self, context, **kwargs):
        """Reset the scene to its initial state."""

        # Restore original render settings
        scene = context.scene
        scene.render.filepath = kwargs["original_filepath"]

        # Remove temporary files
        if os.path.exists(kwargs["extra_filepath"]):
            os.remove(kwargs["extra_filepath"])
        if os.path.exists(kwargs["temp_filepath"]):
            os.remove(kwargs["temp_filepath"])

    def execute(self, context):
        """Execute the operator."""

        scene = context.scene
        if not scene.camera:
            error_message = "No camera found"
            log.error(error_message)
            bpy.ops.comfy.show_error_popup("INVOKE_DEFAULT", error_message=error_message)
            return {'CANCELLED'}

        # Build temp file paths
        temp_folder = get_temp_folder()
        extra_filepath = os.path.join(temp_folder, "tmp.png")  # Extraneous file generated by Blender renderer

        # Initialize scene reset settings
        reset_params = {}
        reset_params["extra_filepath"] = extra_filepath
        reset_params["original_filepath"] = scene.render.filepath

        # Set up the scene for rendering
        scene.render.filepath = extra_filepath

        # Create a new node tree for compositing
        bpy.ops.node.new_compositing_node_group(name="CompositorRender")
        tree = bpy.data.node_groups["CompositorRender"]
        tree.nodes.clear()

        # Create nodes
        rlayers_node = tree.nodes.new(type="CompositorNodeRLayers")
        output_file_node = tree.nodes.new(type="CompositorNodeOutputFile")
        output_file_node.directory = temp_folder
        output_file_node.file_name = ""  # Filename will be set by the file output item
        output_file_node.format.media_type = "IMAGE"
        output_file_node.format.color_mode = "RGB"
        output_file_node.format.file_format = "PNG"
        output_file_node.format.compression = 0
        output_file_node.file_output_items.new("RGBA", self.temp_filename)  # Create input socket blender_render

        # Link nodes
        tree.links.new(rlayers_node.outputs[0], output_file_node.inputs[self.temp_filename])  # From output socket Image to input socket blender_render

        # Render the scene
        scene.compositing_node_group = tree
        bpy.ops.render.render(write_still=True)
        bpy.data.node_groups.remove(tree)

        # Get the rendered filename and path based on current frame
        temp_filename = f"{self.temp_filename}.png"
        temp_filepath = os.path.join(temp_folder, temp_filename)
        reset_params["temp_filepath"] = temp_filepath  # Add the temp filepath to the reset param to delete it later

        # Upload file on ComfyUI server
        try:
            response = upload_file(temp_filepath, type="image")
        except Exception as e:
            # Reset the scene to initial state
            self.reset_scene(context, **reset_params)
            addon_prefs = context.preferences.addons["comfyui_blender"].preferences
            error_message = f"Failed to upload file to ComfyUI server: {addon_prefs.server_address}. {e}"
            log.exception(error_message)
            bpy.ops.comfy.show_error_popup("INVOKE_DEFAULT", error_message=error_message)
            return {'CANCELLED'}

        if response.status_code != 200:
            # Reset the scene to initial state
            self.reset_scene(context, **reset_params)
            error_message = f"Failed to upload file: {response.status_code} - {response.text}"
            log.error(error_message)
            bpy.ops.comfy.show_error_popup("INVOKE_DEFAULT", error_message=error_message)
            return {'CANCELLED'}

        # Delete the previous input image from Blender's data
        current_workflow = scene.current_workflow
        previous_image = getattr(current_workflow, self.workflow_property)
        if previous_image:
            bpy.data.images.remove(previous_image)

        # Build input file paths
        inputs_folder = get_inputs_folder()
        input_subfolder = response.json()["subfolder"]
        input_filename = response.json()["name"]
        input_filepath = os.path.join(inputs_folder, input_subfolder, input_filename)

        # Create the input subfolder if it doesn't exist
        os.makedirs(os.path.join(inputs_folder, input_subfolder), exist_ok=True)

        try:
            # Copy the file to the inputs folder
            shutil.copy(temp_filepath, input_filepath)
            self.report({'INFO'}, f"Input file copied to: {input_filepath}")
        except shutil.SameFileError as e:
            self.report({'INFO'}, f"Input file is already in the inputs folder: {input_filepath}")
        except Exception as e:
            # Reset the scene to initial state
            self.reset_scene(context, **reset_params)
            error_message = f"Failed to copy input file: {e}"
            log.exception(error_message)
            bpy.ops.comfy.show_error_popup("INVOKE_DEFAULT", error_message=error_message)
            return {'CANCELLED'}

        # Load image in the data block
        image = bpy.data.images.load(input_filepath, check_existing=True)

        # Update the workflow property with the image from the data block
        setattr(current_workflow, self.workflow_property, image)

        # Reset the scene to initial state
        self.reset_scene(context, **reset_params)
        return {'FINISHED'}


def register():
    """Register the operator."""

    bpy.utils.register_class(ComfyBlenderOperatorRenderDepthMap)


def unregister():
    """Unregister the operator."""

    bpy.utils.unregister_class(ComfyBlenderOperatorRenderDepthMap)
