from .star_minimax_aio import NODE_CLASS_MAPPINGS as STAR_MINIMAX_AIO_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_MINIMAX_AIO_NODE_DISPLAY_NAMES
from .star_minimax_latent_upscaler import NODE_CLASS_MAPPINGS as STAR_MINIMAX_UPSCALER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_MINIMAX_UPSCALER_NODE_DISPLAY_NAMES
from .star_minimax_h3_lora import NODE_CLASS_MAPPINGS as STAR_MINIMAX_H3_LORA_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_MINIMAX_H3_LORA_NODE_DISPLAY_NAMES

NODE_CLASS_MAPPINGS = {
    **STAR_MINIMAX_AIO_NODE_MAPPINGS,
    **STAR_MINIMAX_UPSCALER_NODE_MAPPINGS,
    **STAR_MINIMAX_H3_LORA_NODE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **STAR_MINIMAX_AIO_NODE_DISPLAY_NAMES,
    **STAR_MINIMAX_UPSCALER_NODE_DISPLAY_NAMES,
    **STAR_MINIMAX_H3_LORA_NODE_DISPLAY_NAMES,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
