# Copyright (c) 2026 exportAnything. All rights reserved.
# SPDX-License-Identifier: MIT

from .nodes import (
    NODE_CLASS_MAPPINGS as _DIRECTOR_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _DIRECTOR_NODE_DISPLAY_NAME_MAPPINGS,
)
from .audio_production_nodes import (
    NODE_CLASS_MAPPINGS as _AUDIO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _AUDIO_NODE_DISPLAY_NAME_MAPPINGS,
)
from .production_planning_nodes import (
    NODE_CLASS_MAPPINGS as _PRODUCTION_PLANNING_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _PRODUCTION_PLANNING_NODE_DISPLAY_NAME_MAPPINGS,
)
from .timed_lyrics_nodes import (
    NODE_CLASS_MAPPINGS as _TIMED_LYRICS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _TIMED_LYRICS_NODE_DISPLAY_NAME_MAPPINGS,
)
from .advertising_contract_nodes import (
    NODE_CLASS_MAPPINGS as _ADVERTISING_CONTRACT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _ADVERTISING_CONTRACT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .advertising_audio_nodes import (
    NODE_CLASS_MAPPINGS as _ADVERTISING_AUDIO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _ADVERTISING_AUDIO_NODE_DISPLAY_NAME_MAPPINGS,
)
from .advertising_planning_nodes import (
    NODE_CLASS_MAPPINGS as _ADVERTISING_PLANNING_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _ADVERTISING_PLANNING_NODE_DISPLAY_NAME_MAPPINGS,
)
from .advertising_finishing_nodes import (
    NODE_CLASS_MAPPINGS as _ADVERTISING_FINISHING_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _ADVERTISING_FINISHING_NODE_DISPLAY_NAME_MAPPINGS,
)
from .advertising_runtime_nodes import (
    NODE_CLASS_MAPPINGS as _ADVERTISING_RUNTIME_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _ADVERTISING_RUNTIME_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **_DIRECTOR_NODE_CLASS_MAPPINGS,
    **_AUDIO_NODE_CLASS_MAPPINGS,
    **_PRODUCTION_PLANNING_NODE_CLASS_MAPPINGS,
    **_TIMED_LYRICS_NODE_CLASS_MAPPINGS,
    **_ADVERTISING_CONTRACT_NODE_CLASS_MAPPINGS,
    **_ADVERTISING_AUDIO_NODE_CLASS_MAPPINGS,
    **_ADVERTISING_PLANNING_NODE_CLASS_MAPPINGS,
    **_ADVERTISING_FINISHING_NODE_CLASS_MAPPINGS,
    **_ADVERTISING_RUNTIME_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **_DIRECTOR_NODE_DISPLAY_NAME_MAPPINGS,
    **_AUDIO_NODE_DISPLAY_NAME_MAPPINGS,
    **_PRODUCTION_PLANNING_NODE_DISPLAY_NAME_MAPPINGS,
    **_TIMED_LYRICS_NODE_DISPLAY_NAME_MAPPINGS,
    **_ADVERTISING_CONTRACT_NODE_DISPLAY_NAME_MAPPINGS,
    **_ADVERTISING_AUDIO_NODE_DISPLAY_NAME_MAPPINGS,
    **_ADVERTISING_PLANNING_NODE_DISPLAY_NAME_MAPPINGS,
    **_ADVERTISING_FINISHING_NODE_DISPLAY_NAME_MAPPINGS,
    **_ADVERTISING_RUNTIME_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
