from .image_tools.aspect_ratio import NODE_CLASS_MAPPINGS as ASPECTRATIO_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ASPECTRATIO_NODE_DISPLAY_NAMES
from .image_tools.aspect_ratio_advanced import NODE_CLASS_MAPPINGS as ASPECTRATIOADV_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ASPECTRATIOADV_NODE_DISPLAY_NAMES
from .samplers.FluxStart import NODE_CLASS_MAPPINGS as FLUXSTART_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FLUXSTART_NODE_DISPLAY_NAMES
from .samplers.SDXLStart import NODE_CLASS_MAPPINGS as SDXLSTART_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SDXLSTART_NODE_DISPLAY_NAMES
from .samplers.SD35Start import NODE_CLASS_MAPPINGS as SD35START_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SD35START_NODE_DISPLAY_NAMES
from .qwen.QwenImageStart import NODE_CLASS_MAPPINGS as QWENIMAGESTART_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QWENIMAGESTART_NODE_DISPLAY_NAMES
from .image_tools.starupscale import NODE_CLASS_MAPPINGS as STARUPSCALE_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARUPSCALE_NODE_DISPLAY_NAMES
from .misc.starwilds import NODE_CLASS_MAPPINGS as STARWILDS_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARWILDS_NODE_DISPLAY_NAMES
from .misc.starwildsadv import NODE_CLASS_MAPPINGS as STARWILDSADV_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARWILDSADV_NODE_DISPLAY_NAMES
from .samplers.fluxstarsampler import NODE_CLASS_MAPPINGS as FLUXSTARSAMPLER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FLUXSTARSAMPLER_NODE_DISPLAY_NAMES
from .text_io.star_conditioning_io import NODE_CLASS_MAPPINGS as STARCOND_IO_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARCOND_IO_NODE_DISPLAY_NAMES
from .image_tools.star_detailenhancer import NODE_CLASS_MAPPINGS as STARDETAILENHANCER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARDETAILENHANCER_NODE_DISPLAY_NAMES
from .infiniteyou.star_infiniteyou_face_swap_mod import NODE_CLASS_MAPPINGS as STARINFINITEYOU_FACESWAP_MOD_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARINFINITEYOU_FACESWAP_MOD_NODE_DISPLAY_NAMES
from .infiniteyou.star_infiniteyou_patch import NODE_CLASS_MAPPINGS as STARINFINITEYOU_PATCH_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARINFINITEYOU_PATCH_NODE_DISPLAY_NAMES
from .infiniteyou.star_infiniteyou_advanced_patch_maker import NODE_CLASS_MAPPINGS as STARINFINITEYOU_ADV_PATCHMAKER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARINFINITEYOU_ADV_PATCHMAKER_NODE_DISPLAY_NAMES
from .samplers.sdstarsampler import NODE_CLASS_MAPPINGS as SDSTARSAMPLER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SDSTARSAMPLER_NODE_DISPLAY_NAMES
from .misc.StarFluxFiller import NODE_CLASS_MAPPINGS as STARFLUXFILLER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARFLUXFILLER_NODE_DISPLAY_NAMES
from .misc.detailstardaemon import NODE_CLASS_MAPPINGS as DETAILSTARDAEMON_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DETAILSTARDAEMON_NODE_DISPLAY_NAMES
from .infiniteyou.starinfiniteyou import NODE_CLASS_MAPPINGS as STARINFINITEYOU_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARINFINITEYOU_NODE_DISPLAY_NAMES
from .image_tools.starlatentinput import NODE_CLASS_MAPPINGS as STARLATENTINPUT_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARLATENTINPUT_NODE_DISPLAY_NAMES
from .image_tools.StarLatentInput2 import NODE_CLASS_MAPPINGS as STARLATENTINPUT2_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARLATENTINPUT2_NODE_DISPLAY_NAMES
from .image_tools.StarImage2Latent import NODE_CLASS_MAPPINGS as STARIMAGE2LATENT_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARIMAGE2LATENT_NODE_DISPLAY_NAMES
from .text_io.StarNode import NODE_CLASS_MAPPINGS as STARNODE_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARNODE_NODE_DISPLAY_NAMES
from .text_io.StarNode2 import NODE_CLASS_MAPPINGS as STARNODE2_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARNODE2_NODE_DISPLAY_NAMES
from .text_io.startextfilter import NODE_CLASS_MAPPINGS as STARTEXTFILTER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARTEXTFILTER_NODE_DISPLAY_NAMES
from .grid.stargridcomposer import NODE_CLASS_MAPPINGS as STARGRIDCOMPOSER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARGRIDCOMPOSER_NODE_DISPLAY_NAMES
from .grid.stargridbatchers import NODE_CLASS_MAPPINGS as STARGRIDBATCHERS_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARGRIDBATCHERS_NODE_DISPLAY_NAMES
from .text_io.startextinput import NODE_CLASS_MAPPINGS as STARTEXTINPUT_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARTEXTINPUT_NODE_DISPLAY_NAMES
from .misc.starfaceloader import NODE_CLASS_MAPPINGS as STARFACELOADER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARFACELOADER_NODE_DISPLAY_NAMES
from .image_tools.StarDivisibleDimension import NODE_CLASS_MAPPINGS as STARDIVISIBLEDIMENSION_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARDIVISIBLEDIMENSION_NODE_DISPLAY_NAMES
from .external.StarNewsScraper import NODE_CLASS_MAPPINGS as STARNEWS_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARNEWS_NODE_DISPLAY_NAMES
from .misc.StarLora import NODE_CLASS_MAPPINGS as STARLORA_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARLORA_NODE_DISPLAY_NAMES
from .misc.star_dynamic_lora import NODE_CLASS_MAPPINGS as STAR_DYNAMIC_LORA_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_DYNAMIC_LORA_NODE_DISPLAY_NAME_MAPPINGS
from .misc.star_lora_weight_normalizer import NODE_CLASS_MAPPINGS as STAR_LORA_WEIGHT_NORMALIZER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_LORA_WEIGHT_NORMALIZER_NODE_DISPLAY_NAME_MAPPINGS
from .text_io.StarPSDSaver import NODE_CLASS_MAPPINGS as STARPSDSAVER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARPSDSAVER_NODE_DISPLAY_NAMES
from .text_io.StarPSDSaver2 import NODE_CLASS_MAPPINGS as STARPSDSAVER2_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARPSDSAVER2_NODE_DISPLAY_NAMES
from .text_io.StarPSDSaverAdvLayers import NODE_CLASS_MAPPINGS as STARPSDSAVERADVLAYERS_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARPSDSAVERADVLAYERS_NODE_DISPLAY_NAMES
from .text_io.startextstorage import NODE_CLASS_MAPPINGS as STARTEXTSTORAGE_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARTEXTSTORAGE_NODE_DISPLAY_NAMES
from .text_io.starwatermark import NODE_CLASS_MAPPINGS as STARWATERMARK_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARWATERMARK_NODE_DISPLAY_NAMES
from .text_io.StarDenoiseSlider import NODE_CLASS_MAPPINGS as STARDENOISESLIDER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARDENOISESLIDER_NODE_DISPLAY_NAMES
from .samplers.starsamplersettings_nodes import NODE_CLASS_MAPPINGS as STARSAMPLERSETTINGS_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARSAMPLERSETTINGS_NODE_DISPLAY_NAMES
from .text_io.StarPaletteExtractor import NODE_CLASS_MAPPINGS as STARPALETTEEXTRACTOR_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARPALETTEEXTRACTOR_NODE_DISPLAY_NAMES
from .image_tools.star_highpass import NODE_CLASS_MAPPINGS as STAR_SPECIAL_FILTERS_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_SPECIAL_FILTERS_NODE_DISPLAY_NAME_MAPPINGS
from .text_io.StarShowLastFrame import NODE_CLASS_MAPPINGS as STARSHOWLASTFRAME_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARSHOWLASTFRAME_NODE_DISPLAY_NAMES
from .image_tools.StarAspectVideoRatio import NODE_CLASS_MAPPINGS as STARASPECTVIDEORATIO_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARASPECTVIDEORATIO_NODE_DISPLAY_NAMES
from .text_io.StarShowLastFrame import NODE_CLASS_MAPPINGS as STARSHOWLASTFRAME_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARSHOWLASTFRAME_NODE_DISPLAY_NAMES
from .image_tools.StarAspectVideoRatio import NODE_CLASS_MAPPINGS as STARASPECTVIDEORATIO_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARASPECTVIDEORATIO_NODE_DISPLAY_NAMES
from .image_tools.star_random_image_loader import NODE_CLASS_MAPPINGS as STAR_RANDOM_IMAGE_LOADER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_RANDOM_IMAGE_LOADER_NODE_DISPLAY_NAME_MAPPINGS
from .text_io.star_save_panorama_jpeg import NODE_CLASS_MAPPINGS as STAR_SAVE_PANORAMA_JPEG_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_SAVE_PANORAMA_JPEG_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools.star_frame_from_video import NODE_CLASS_MAPPINGS as STAR_FRAME_FROM_VIDEO_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_FRAME_FROM_VIDEO_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools.star_image_loader_1by1 import NODE_CLASS_MAPPINGS as STAR_IMAGE_LOADER_1BY1_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_IMAGE_LOADER_1BY1_NODE_DISPLAY_NAME_MAPPINGS
from .text_io.star_icon_exporter import NODE_CLASS_MAPPINGS as STAR_ICON_EXPORTER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_ICON_EXPORTER_NODE_DISPLAY_NAME_MAPPINGS
from .qwen.star_qwen_image_ratio import NODE_CLASS_MAPPINGS as STAR_QWEN_IMAGE_RATIO_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_IMAGE_RATIO_NODE_DISPLAY_NAME_MAPPINGS
from .qwen.star_qwen_wan_ratio import NODE_CLASS_MAPPINGS as STAR_QWEN_WAN_RATIO_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_WAN_RATIO_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools.star_latent_ratio_megapixel import NODE_CLASS_MAPPINGS as STAR_LATENT_RATIO_MEGAPIXEL_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_LATENT_RATIO_MEGAPIXEL_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools.star_latent_resize import NODE_CLASS_MAPPINGS as STAR_LATENT_RESIZE_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_LATENT_RESIZE_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools.star_apply_overlay_depth import NODE_CLASS_MAPPINGS as STAR_APPLY_OVERLAY_DEPTH_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_APPLY_OVERLAY_DEPTH_NODE_DISPLAY_NAME_MAPPINGS
from .qwen.star_qwen_image_edit_inputs import NODE_CLASS_MAPPINGS as STAR_QWEN_IMAGE_EDIT_INPUTS_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_IMAGE_EDIT_INPUTS_NODE_DISPLAY_NAME_MAPPINGS
from .qwen.star_qwen_edit_encoder import NODE_CLASS_MAPPINGS as STAR_QWEN_EDIT_ENCODER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_EDIT_ENCODER_NODE_DISPLAY_NAME_MAPPINGS
from .qwen.star_image_edit_qwen_kontext import NODE_CLASS_MAPPINGS as STAR_IMAGE_EDIT_QWEN_KONTEXT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_IMAGE_EDIT_QWEN_KONTEXT_NODE_DISPLAY_NAME_MAPPINGS
from .text_io.star_save_folder_string import NODE_CLASS_MAPPINGS as STAR_SAVE_FOLDER_STRING_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_SAVE_FOLDER_STRING_NODE_DISPLAY_NAME_MAPPINGS
from .external.star_ollama_sysprompter_jc import NODE_CLASS_MAPPINGS as STAR_OLLAMA_SYSPROMPTER_JC_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_OLLAMA_SYSPROMPTER_JC_NODE_DISPLAY_NAME_MAPPINGS
from .external.star_nano_banana import NODE_CLASS_MAPPINGS as STAR_NANO_BANANA_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_NANO_BANANA_NODE_DISPLAY_NAME_MAPPINGS
from .text_io.star_duplicate_model_finder import NODE_CLASS_MAPPINGS as STAR_DUPLICATE_MODEL_FINDER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_DUPLICATE_MODEL_FINDER_NODE_DISPLAY_NAME_MAPPINGS
from .qwen.star_qwen_edit_plus_conditioner import NODE_CLASS_MAPPINGS as STAR_QWEN_EDIT_PLUS_CONDITIONER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_EDIT_PLUS_CONDITIONER_NODE_DISPLAY_NAME_MAPPINGS
from .qwen.star_qwen_rebalance_prompter import NODE_CLASS_MAPPINGS as STAR_QWEN_REBALANCE_PROMPTER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_REBALANCE_PROMPTER_NODE_DISPLAY_NAME_MAPPINGS
from .qwen.star_qwen_regional_prompter import NODE_CLASS_MAPPINGS as STAR_QWEN_REGIONAL_PROMPTER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_REGIONAL_PROMPTER_NODE_DISPLAY_NAME_MAPPINGS
from .samplers.star_sampler import NODE_CLASS_MAPPINGS as STAR_SAMPLER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_SAMPLER_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools.star_simple_filters import NODE_CLASS_MAPPINGS as STAR_SIMPLE_FILTERS_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_SIMPLE_FILTERS_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools.star_radial_blur import NODE_CLASS_MAPPINGS as STAR_RADIAL_BLUR_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_RADIAL_BLUR_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools.star_black_white import NODE_CLASS_MAPPINGS as STAR_BLACK_WHITE_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_BLACK_WHITE_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools.star_hdr_effects import NODE_CLASS_MAPPINGS as STAR_HDR_EFFECTS_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_HDR_EFFECTS_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools.star_sd_upscale_refiner import NODE_CLASS_MAPPINGS as STAR_SD_UPSCALE_REFINER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_SD_UPSCALE_REFINER_NODE_DISPLAY_NAME_MAPPINGS
from .misc.star_gemini_refiner import NODE_CLASS_MAPPINGS as STAR_GEMINI_REFINER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_GEMINI_REFINER_NODE_DISPLAY_NAME_MAPPINGS
from .misc.star_fp8_converter import NODE_CLASS_MAPPINGS as STAR_FP8_CONVERTER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_FP8_CONVERTER_NODE_DISPLAY_NAME_MAPPINGS
from .misc.star_flowmatch_option import NODE_CLASS_MAPPINGS as STAR_FLOWMATCH_OPTION_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_FLOWMATCH_OPTION_NODE_DISPLAY_NAME_MAPPINGS
from .misc.star_model_packer import NODE_CLASS_MAPPINGS as STAR_MODEL_PACKER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_MODEL_PACKER_NODE_DISPLAY_NAME_MAPPINGS
from .misc.star_stop_and_go import NODE_CLASS_MAPPINGS as STAR_STOP_AND_GO_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_STOP_AND_GO_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools.star_meta_injector import NODE_CLASS_MAPPINGS as STAR_META_INJECTOR_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_META_INJECTOR_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools.star_image_loop import NODE_CLASS_MAPPINGS as STAR_IMAGE_LOOP_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_IMAGE_LOOP_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools.star_video_loop import NODE_CLASS_MAPPINGS as STAR_VIDEO_LOOP_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_VIDEO_LOOP_NODE_DISPLAY_NAME_MAPPINGS

import os
import shutil
import sys

# Try to import folder_paths from ComfyUI
try:
    import folder_paths
except ImportError:
    print("Warning: Could not import folder_paths from ComfyUI")
    folder_paths = None

NODE_CLASS_MAPPINGS = {
    **FLUXSTART_NODE_MAPPINGS,
    **SDXLSTART_NODE_MAPPINGS,
    **SD35START_NODE_MAPPINGS,
    **QWENIMAGESTART_NODE_MAPPINGS,
    **STARUPSCALE_NODE_MAPPINGS,
    **STARWILDS_NODE_MAPPINGS,
    **STARWILDSADV_NODE_MAPPINGS,
    **FLUXSTARSAMPLER_NODE_MAPPINGS,
    **SDSTARSAMPLER_NODE_MAPPINGS,
    **STARFLUXFILLER_NODE_MAPPINGS,
    **STARNEWS_NODE_MAPPINGS,
    **STARTEXTFILTER_NODE_MAPPINGS,
    **DETAILSTARDAEMON_NODE_MAPPINGS,
    **STARNODE_NODE_MAPPINGS,
    **STARNODE2_NODE_MAPPINGS,
    **STARTEXTINPUT_NODE_MAPPINGS,
    **STARFACELOADER_NODE_MAPPINGS,
    **STARLATENTINPUT_NODE_MAPPINGS,
    **STARLATENTINPUT2_NODE_MAPPINGS,
    **STARIMAGE2LATENT_NODE_MAPPINGS,
    **STARDIVISIBLEDIMENSION_NODE_MAPPINGS,
    **STARLORA_NODE_MAPPINGS,
    **STAR_DYNAMIC_LORA_NODE_MAPPINGS,
    **STAR_LORA_WEIGHT_NORMALIZER_NODE_MAPPINGS,
    **STARPSDSAVER_NODE_MAPPINGS,
    **STARPSDSAVER2_NODE_MAPPINGS,
    **STARPSDSAVERADVLAYERS_NODE_MAPPINGS,
    **STARTEXTSTORAGE_NODE_MAPPINGS,
    **STARDENOISESLIDER_NODE_MAPPINGS,
    **STARSAMPLERSETTINGS_NODE_MAPPINGS,
    **ASPECTRATIO_NODE_MAPPINGS,
    **ASPECTRATIOADV_NODE_MAPPINGS,
    **STARCOND_IO_NODE_MAPPINGS,
    **STARINFINITEYOU_NODE_MAPPINGS,
    **STARINFINITEYOU_PATCH_NODE_MAPPINGS,
    **STARINFINITEYOU_ADV_PATCHMAKER_NODE_MAPPINGS,
    **STARINFINITEYOU_FACESWAP_MOD_NODE_MAPPINGS,
    **STARGRIDCOMPOSER_NODE_MAPPINGS,
    **STARGRIDBATCHERS_NODE_MAPPINGS,
    **STARWATERMARK_NODE_MAPPINGS,
    **STARPALETTEEXTRACTOR_NODE_MAPPINGS,
    **STAR_SPECIAL_FILTERS_NODE_MAPPINGS,
    **STAR_RANDOM_IMAGE_LOADER_NODE_CLASS_MAPPINGS,
    **STAR_SAVE_PANORAMA_JPEG_NODE_CLASS_MAPPINGS,
    **STAR_FRAME_FROM_VIDEO_NODE_CLASS_MAPPINGS,
    **STAR_IMAGE_LOADER_1BY1_NODE_CLASS_MAPPINGS,
    **STAR_ICON_EXPORTER_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_IMAGE_RATIO_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_WAN_RATIO_NODE_CLASS_MAPPINGS,
    **STAR_LATENT_RATIO_MEGAPIXEL_NODE_CLASS_MAPPINGS,
    **STAR_LATENT_RESIZE_NODE_CLASS_MAPPINGS,
    **STAR_APPLY_OVERLAY_DEPTH_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_IMAGE_EDIT_INPUTS_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_EDIT_ENCODER_NODE_CLASS_MAPPINGS,
    **STAR_IMAGE_EDIT_QWEN_KONTEXT_NODE_CLASS_MAPPINGS,
    **STAR_SAVE_FOLDER_STRING_NODE_CLASS_MAPPINGS,
    **STAR_OLLAMA_SYSPROMPTER_JC_NODE_CLASS_MAPPINGS,
    **STAR_NANO_BANANA_NODE_CLASS_MAPPINGS,
    **STAR_DUPLICATE_MODEL_FINDER_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_EDIT_PLUS_CONDITIONER_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_REBALANCE_PROMPTER_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_REGIONAL_PROMPTER_NODE_CLASS_MAPPINGS,
    **STAR_SAMPLER_NODE_CLASS_MAPPINGS,
    **STAR_SIMPLE_FILTERS_NODE_CLASS_MAPPINGS,
    **STAR_RADIAL_BLUR_NODE_CLASS_MAPPINGS,
    **STAR_BLACK_WHITE_NODE_CLASS_MAPPINGS,
    **STAR_HDR_EFFECTS_NODE_CLASS_MAPPINGS,
    **STAR_SD_UPSCALE_REFINER_NODE_CLASS_MAPPINGS,
    **STAR_GEMINI_REFINER_NODE_MAPPINGS,
    **STAR_FP8_CONVERTER_NODE_MAPPINGS,
    **STAR_FLOWMATCH_OPTION_NODE_MAPPINGS,
    **STAR_MODEL_PACKER_NODE_MAPPINGS,
    **STAR_STOP_AND_GO_NODE_MAPPINGS,
    **STAR_META_INJECTOR_NODE_MAPPINGS,
    **STAR_IMAGE_LOOP_NODE_MAPPINGS,
    **STAR_VIDEO_LOOP_NODE_MAPPINGS,
    # Manual add for Star Detail Enhancer
    "AdaptiveDetailEnhancement": STARDETAILENHANCER_NODE_MAPPINGS["AdaptiveDetailEnhancement"],
    # Manual add for StarShowLastFrame
    "Star_Show_Last_Frame": STARSHOWLASTFRAME_NODE_MAPPINGS["Star_Show_Last_Frame"],
    # Manual add for StarAspectVideoRatio
    "Starnodes_Aspect_Video_Ratio": STARASPECTVIDEORATIO_NODE_MAPPINGS["Starnodes_Aspect_Video_Ratio"],

}

NODE_DISPLAY_NAME_MAPPINGS = {
    **FLUXSTART_NODE_DISPLAY_NAMES,
    **SDXLSTART_NODE_DISPLAY_NAMES,
    **SD35START_NODE_DISPLAY_NAMES,
    **QWENIMAGESTART_NODE_DISPLAY_NAMES,
    **STARUPSCALE_NODE_DISPLAY_NAMES,
    **STARWILDS_NODE_DISPLAY_NAMES,
    **STARWILDSADV_NODE_DISPLAY_NAMES,
    **FLUXSTARSAMPLER_NODE_DISPLAY_NAMES,
    **SDSTARSAMPLER_NODE_DISPLAY_NAMES,
    **STARFLUXFILLER_NODE_DISPLAY_NAMES,
    **STARNEWS_NODE_DISPLAY_NAMES,
    **STARTEXTFILTER_NODE_DISPLAY_NAMES,
    **DETAILSTARDAEMON_NODE_DISPLAY_NAMES,
    **STARNODE_NODE_DISPLAY_NAMES,
    **STARNODE2_NODE_DISPLAY_NAMES,
    **STARTEXTINPUT_NODE_DISPLAY_NAMES,
    **STARFACELOADER_NODE_DISPLAY_NAMES,
    **STARLATENTINPUT_NODE_DISPLAY_NAMES,
    **STARLATENTINPUT2_NODE_DISPLAY_NAMES,
    **STARIMAGE2LATENT_NODE_DISPLAY_NAMES,
    **STARDIVISIBLEDIMENSION_NODE_DISPLAY_NAMES,
    **STARLORA_NODE_DISPLAY_NAMES,
    **STAR_DYNAMIC_LORA_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_LORA_WEIGHT_NORMALIZER_NODE_DISPLAY_NAME_MAPPINGS,
    **STARPSDSAVER_NODE_DISPLAY_NAMES,
    **STARPSDSAVER2_NODE_DISPLAY_NAMES,
    **STARPSDSAVERADVLAYERS_NODE_DISPLAY_NAMES,
    **STARTEXTSTORAGE_NODE_DISPLAY_NAMES,
    **STARDENOISESLIDER_NODE_DISPLAY_NAMES,
    **STARSAMPLERSETTINGS_NODE_DISPLAY_NAMES,
    **ASPECTRATIO_NODE_DISPLAY_NAMES,
    **ASPECTRATIOADV_NODE_DISPLAY_NAMES,
    **STARCOND_IO_NODE_DISPLAY_NAMES,
    **STARINFINITEYOU_NODE_DISPLAY_NAMES,
    **STARINFINITEYOU_PATCH_NODE_DISPLAY_NAMES,
    **STARINFINITEYOU_ADV_PATCHMAKER_NODE_DISPLAY_NAMES,
    **STARINFINITEYOU_FACESWAP_MOD_NODE_DISPLAY_NAMES,
    **STARGRIDCOMPOSER_NODE_DISPLAY_NAMES,
    **STARGRIDBATCHERS_NODE_DISPLAY_NAMES,
    **STARWATERMARK_NODE_DISPLAY_NAMES,
    **STARPALETTEEXTRACTOR_NODE_DISPLAY_NAMES,
    **STAR_SPECIAL_FILTERS_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_RANDOM_IMAGE_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_SAVE_PANORAMA_JPEG_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_FRAME_FROM_VIDEO_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_IMAGE_LOADER_1BY1_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_ICON_EXPORTER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_IMAGE_RATIO_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_WAN_RATIO_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_LATENT_RATIO_MEGAPIXEL_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_LATENT_RESIZE_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_APPLY_OVERLAY_DEPTH_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_IMAGE_EDIT_INPUTS_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_EDIT_ENCODER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_IMAGE_EDIT_QWEN_KONTEXT_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_SAVE_FOLDER_STRING_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_OLLAMA_SYSPROMPTER_JC_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_NANO_BANANA_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_DUPLICATE_MODEL_FINDER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_EDIT_PLUS_CONDITIONER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_REBALANCE_PROMPTER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_REGIONAL_PROMPTER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_SAMPLER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_SIMPLE_FILTERS_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_RADIAL_BLUR_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_BLACK_WHITE_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_HDR_EFFECTS_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_SD_UPSCALE_REFINER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_GEMINI_REFINER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_FP8_CONVERTER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_FLOWMATCH_OPTION_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_MODEL_PACKER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_STOP_AND_GO_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_META_INJECTOR_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_IMAGE_LOOP_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_VIDEO_LOOP_NODE_DISPLAY_NAME_MAPPINGS,
    # Manual add for Star Detail Enhancer
    "AdaptiveDetailEnhancement": STARDETAILENHANCER_NODE_DISPLAY_NAMES["AdaptiveDetailEnhancement"],
    # Manual add for StarShowLastFrame
    "Star_Show_Last_Frame": STARSHOWLASTFRAME_NODE_DISPLAY_NAMES["Star_Show_Last_Frame"],
    # Manual add for StarAspectVideoRatio
    "Starnodes_Aspect_Video_Ratio": STARASPECTVIDEORATIO_NODE_DISPLAY_NAMES["Starnodes_Aspect_Video_Ratio"],

}

__version__ = "1.9.4"

# Define the web directory for ComfyUI to find our JavaScript files
WEB_DIRECTORY = "./web"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']

# Copy wildcards folder to ComfyUI main directory if it doesn't exist
def copy_wildcards_folder():
    if folder_paths is None:
        print("Warning: Could not copy wildcards folder because folder_paths is not available")
        return
    
    # Get the path to the main ComfyUI directory
    comfyui_base_path = folder_paths.base_path
    
    # Get the path to the wildcards folder in the StarNodes extension
    current_dir = os.path.dirname(os.path.abspath(__file__))
    source_wildcards_path = os.path.join(current_dir, 'wildcards')
    
    # Get the path to the destination wildcards folder in the main ComfyUI directory
    dest_wildcards_path = os.path.join(comfyui_base_path, 'wildcards')
    
    # Check if the wildcards folder already exists in the main ComfyUI directory
    if not os.path.exists(dest_wildcards_path):
        try:
            print(f"StarNodes: Copying wildcards folder to {dest_wildcards_path}")
            # Create the destination directory if it doesn't exist
            os.makedirs(dest_wildcards_path, exist_ok=True)
            
            # Copy all files from the source wildcards folder to the destination
            for item in os.listdir(source_wildcards_path):
                source_item = os.path.join(source_wildcards_path, item)
                dest_item = os.path.join(dest_wildcards_path, item)
                
                # Skip if the destination file already exists
                if os.path.exists(dest_item):
                    continue
                
                if os.path.isfile(source_item):
                    shutil.copy2(source_item, dest_item)
                    print(f"StarNodes: Copied wildcard file {item}")
            
            print("StarNodes: Successfully copied wildcards folder to ComfyUI main directory")
        except Exception as e:
            print(f"StarNodes: Error copying wildcards folder: {str(e)}")
    else:
        # Check if we need to copy any missing wildcard files
        for item in os.listdir(source_wildcards_path):
            source_item = os.path.join(source_wildcards_path, item)
            dest_item = os.path.join(dest_wildcards_path, item)
            
            # Skip if the destination file already exists
            if os.path.exists(dest_item):
                continue
            
            if os.path.isfile(source_item):
                try:
                    shutil.copy2(source_item, dest_item)
                    print(f"StarNodes: Copied missing wildcard file {item}")
                except Exception as e:
                    print(f"StarNodes: Error copying wildcard file {item}: {str(e)}")

# Run the copy function when the module is imported
copy_wildcards_folder()

# Serve web assets for Starnodes features
try:
    import json
    from server import PromptServer
    from aiohttp import web

    _OTTERS_DIR = os.path.join(os.path.dirname(__file__), 'web', 'js', 'otters')
    _EDITPROMPTS_PATH = os.path.join(os.path.dirname(__file__), 'editprompts.json')

    @PromptServer.instance.routes.get("/starnodes/otters/{filename:path}")
    async def starnodes_serve_otter_sprite(request):
        filename = request.match_info['filename']
        safe_name = os.path.basename(filename)
        target = os.path.join(_OTTERS_DIR, safe_name)
        if os.path.isfile(target):
            return web.FileResponse(target)
        return web.Response(status=404)

    @PromptServer.instance.routes.get("/starnodes/editprompts")
    async def starnodes_editprompts(request):
        try:
            if os.path.isfile(_EDITPROMPTS_PATH):
                with open(_EDITPROMPTS_PATH, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                return web.json_response(data)
        except Exception as e:
            print(f"Error serving editprompts: {e}")
        return web.json_response({"error": "not found"}, status=404)
except Exception:
    # If server or aiohttp isn't available yet, silently skip
    pass
