[build-system]
requires	= ["setuptools>=70.0"]
build-backend	= "setuptools.build_meta"

[project]
name	= "ComfyUI-outputlists_combiner"
version	= "0.0.20"
description	= """Multi-prompt, multi image generation & video batch processing in a single run to sequentially process multiple assets at once!
Includes the only clean correct and customizable XY grid plots for ComfyUI based on data lists. Works with every workflow. XY images XYZ super grid plots & video grids for Minimax H3 WAN LTX & Hunyuan 3D
Generator for multiple prompt lists & text combinations to combine prompts & resolutions variants + ChatGPT Claude LLM
Inspect combo tool to retrieve a list of models. Combine LoRA models strength & trigger words
Compare samplers & schedulers of Flux Krea Zit Turbo
Spreadsheets for batch processing (Microsoft Office Excel LibreOffice Calc CSV TSV markdown tables)
Load any file from disk (plaintext base64 binary jsonpath http api) directory listing & path glob patterns, load video file & metadata
Iterator nodes to foreach lists simpler than for-loops & while-loops for efficiency
Integrates well with essentials like Crystools ImpactPack KJNodes EasyUse tinyterra"""

authors	= [{name = "Gerold Meisinger"}]
readme	= "README.md"
license	= { text="GNU General Public License v3" }
requires-python	= ">=3.10"
classifiers	= []
dependencies	= ["nums-from-string", "fastnumbers", "jsonpath_ng", "pandas", "odfpy", "openpyxl", "xlrd", "pyxlsb", "chardet", "skia-python", "pyexiftool", "deepdiff"]

[tool.open_manager]
# incompatible = ["numpy>=2.0"]                   # declare known conflicts with other packages
# source = "github"                               # prefer installing from the repository
# branch = "main"                                 # default branch to install from
docs = "https://github.com/geroldmeisinger/ComfyUI-outputlists-combiner"               # documentation URL
funding = "https://buymeacoffee.com/geroldmeisinger"               # funding URL
release_note = """0.0.19 fixed file glob limit in Load Any File, cleanup node promotion
0.0.15 added Bake String node
0.0.14 restructed Spreadsheet OutputList, deprecated Formatted String in favor of Comfy Core Format Text
0.0.13 fixed nested Iterate loop nodes
0.0.12 added Iterate loop nodes, added separator field in SpreadsheetOutputList
0.0.11 fixed understaffed XYZGridPlot, fixed node documentation language codes
0.0.10 fixed font_size in XYZGridPlot, fixed Load Any File, translated node documentation""" # your note on the current release, 600 chars
example_workflows = [ # list example workflows to load
	"workflows/01S_Simple_OutputList.json",
	"workflows/02S_Combine_Prompts.json",
	"workflows/03S_Combine_Numbers.json",
	"workflows/04S_Combine_Samplers_Schedulers.json",
	"workflows/05S_Combine_RowCol_Filename.json",
	"workflows/06S_Compare_LoRAModel_LoRAStrength.json",
	"workflows/07S_XYZ-GridPlot.json",
	"workflows/08S_LoadMultipleFiles.json",
	"workflows/09S_IterateLoopNodes.json",
	"workflows/10S_RepeatOutputLists.json",
	"workflows/11S_CycleOutputLists.json",
	"workflows/12A_AnimatingLoRAStrength.json",
	"workflows/13A_CheckpointsImmediateSave.json",
	"workflows/14A_XYZGridPlotSupergrids.json",
	"workflows/15A_XYZGridPlotImmediateSave.json",
	"workflows/16A_LoadWithFormattedString.json",
	"workflows/17A_BakeStringIterateLoopNodes.json",
	"workflows/18A_BakeStringXYZGridPlotSupergrids.json",
	"workflows/19A_BakeStringLoadAnyFile.json",
	"workflows/20A_DiscriminateMultipleFiles.json",
	"workflows/21A_NestedIterateLoopNodes.json",
	"workflows/22A_PromptManager.json",
	"workflows/23V_Duration.json",
	"workflows/24V_Resolution.json",
	"workflows/25V_Duration_Timer_CSV.json",
	"workflows/26V_Spreadsheet_Videos.json",
	"workflows/27V_LoadMultipleVideos.json",
	"workflows/28V_Resolution_Duration_Timer_CSV.json",
	"workflows/29V_XYZGridPlotVideo.json"
]
# themes = ["themes/my-theme.json"]	# list themes to offer
gallery = [	# images to show off the pack, up to 24, `png`, `jpg`, `jpeg`, `gif`, `webp` and `avif`
	"https://raw.githubusercontent.com/geroldmeisinger/ComfyUI-outputlists-combiner/refs/heads/main/gallery/01_Promo.mp4",
	"https://raw.githubusercontent.com/geroldmeisinger/ComfyUI-outputlists-combiner/refs/heads/main/gallery/02_XYZ-GridPlot.mp4",
	"https://raw.githubusercontent.com/geroldmeisinger/ComfyUI-outputlists-combiner/refs/heads/main/gallery/03_AnimatingLoRAStrength.mp4",
	"https://raw.githubusercontent.com/geroldmeisinger/ComfyUI-outputlists-combiner/refs/heads/main/gallery/04_OutputLists.mp4",
	"https://raw.githubusercontent.com/geroldmeisinger/ComfyUI-outputlists-combiner/refs/heads/main/gallery/05_Spreadsheet_Video.mp4",
	"https://raw.githubusercontent.com/geroldmeisinger/ComfyUI-outputlists-combiner/refs/heads/main/gallery/06_InspectCombo_All.mp4"
	#  "docs/before.png",                            #   a path in your repository
	#  "https://cdn.example.com/after.webp",         #   or an image hosted anywhere
]

[project.optional-dependencies]
dev = [
	"bump-my-version"	,
	"coverage"	, # testing
	"mypy"	, # linting
	"pre-commit"	, # runs linting on commit
	"pytest"	, # testing
	"ruff"	, # linting
]

[project.urls]
Repository	= "https://github.com/geroldmeisinger/ComfyUI-outputlists-combiner"
BugTracker	= "https://github.com/geroldmeisinger/ComfyUI-outputlists-combiner/issues"
Documentation	= "https://github.com/geroldmeisinger/ComfyUI-outputlists-combiner"

[tool.comfy]
PublisherId	= "geroldmeisinger"
DisplayName	= "! OutputLists Combiner"
Icon	= "https://raw.githubusercontent.com/geroldmeisinger/ComfyUI-outputlists-combiner/refs/heads/main/icon.gif" # File types: SVG, PNG, JPG, or GIF, Maximum resolution: 400px x 400px, Aspect ratio should be square
Banner	= "https://raw.githubusercontent.com/geroldmeisinger/ComfyUI-outputlists-combiner/refs/heads/main/banner.png" # URL to a larger banner image that will be displayed on the ComfyUI Registry and ComfyUI-Manager. File types: SVG, PNG, JPG, or GIF, Aspect ratio: 21:9
Tags	= []
Repository	= "https://github.com/geroldmeisinger/ComfyUI-outputlists-combiner"
includes	= []

[tool.setuptools.package-data]
"*" = ["*.*"]

[tool.pytest.ini_options]
minversion	= "8.0"
testpaths	= ["tests",]

[tool.mypy]
files = "."

# Use strict defaults
strict	= true
warn_unreachable	= true
warn_no_return	= true

[[tool.mypy.overrides]]
# Don't require test functions to include types
module	= "tests.*"
allow_untyped_defs	= true
disable_error_code	= "attr-defined"

[tool.ruff]
# extend-exclude	= ["static", "ci/templates"]
line-length	= 140
src	= ["src"] #, "tests"]
target-version	= "py39"

# Add rules to ban exec/eval
[tool.ruff.lint]
select = [
	"S102"	, # exec-builtin
	"S307"	, # eval-used
	"W293"	,
	"F"	, # The "F" series in Ruff stands for "Pyflakes" rules, which catch various Python syntax errors and undefined names.
	# See all rules here: https://docs.astral.sh/ruff/rules/#pyflakes-f
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"
