# Import nodes from modules
from .unianimate.nodes import NODE_CLASS_MAPPINGS as UNIANIMATE_NODE_CLASS_MAPPINGS
from .unianimate.nodes import NODE_DISPLAY_NAME_MAPPINGS as UNIANIMATE_NODE_DISPLAY_NAME_MAPPINGS

# Import from nodes.py (not the nodes/ directory) using simple relative import
from .nodes import NODE_CLASS_MAPPINGS as UTILITY_NODE_CLASS_MAPPINGS
from .nodes import NODE_DISPLAY_NAME_MAPPINGS as UTILITY_NODE_DISPLAY_NAME_MAPPINGS

# Combine node mappings
NODE_CLASS_MAPPINGS = {**UNIANIMATE_NODE_CLASS_MAPPINGS, **UTILITY_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**UNIANIMATE_NODE_DISPLAY_NAME_MAPPINGS, **UTILITY_NODE_DISPLAY_NAME_MAPPINGS}

# Web directory for JavaScript files
WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]