[project]
name = "comfyui-ppm"
version = "1.1.10"
description = "Attention Couple for SDXL and Anima; NegPiP (negative weights in prompts) for SDXL and Anima; etc."
license = "AGPL-3.0-or-later"
license-files = ["LICENSE"]

[project.urls]
Repository = "https://github.com/pamparamm/ComfyUI-ppm"

[dependency-groups]
dev = ["pyrefly", "ruff"]

[tool.comfy]
PublisherId = "pamparamm"
DisplayName = "ComfyUI-ppm"
Icon = ""

[tool.pyrefly]
search-path = ["./", "../../"]

[tool.ruff]
line-length = 120
indent-width = 4
lint.select = ["S307", "S102", "T", "W", "F", "I"]
src = ["./", "../../"]

[tool.uv]
package = false
