# Copyright (c) 2025 Andrea Pozzetti
# SPDX-License-Identifier: MIT
"""
ComfyUI SAM 3D Body Custom Nodes

Aggregate all node class mappings from submodules.
"""

# Import node mappings from processing modules
from .load_model import NODE_CLASS_MAPPINGS as LOAD_MAPPINGS
from .load_model import NODE_DISPLAY_NAME_MAPPINGS as LOAD_DISPLAY_MAPPINGS

from .load_mesh import NODE_CLASS_MAPPINGS as LOAD_MESH_MAPPINGS
from .load_mesh import NODE_DISPLAY_NAME_MAPPINGS as LOAD_MESH_DISPLAY_MAPPINGS

from .process import NODE_CLASS_MAPPINGS as PROCESS_MAPPINGS
from .process import NODE_DISPLAY_NAME_MAPPINGS as PROCESS_DISPLAY_MAPPINGS

from .visualize import NODE_CLASS_MAPPINGS as VIS_MAPPINGS
from .visualize import NODE_DISPLAY_NAME_MAPPINGS as VIS_DISPLAY_MAPPINGS

from .preview import NODE_CLASS_MAPPINGS as PREVIEW_MAPPINGS
from .preview import NODE_DISPLAY_NAME_MAPPINGS as PREVIEW_DISPLAY_MAPPINGS

from .export import NODE_CLASS_MAPPINGS as EXPORT_MAPPINGS
from .export import NODE_DISPLAY_NAME_MAPPINGS as EXPORT_DISPLAY_MAPPINGS

from .skeleton_io import NODE_CLASS_MAPPINGS as SKELETON_IO_MAPPINGS
from .skeleton_io import NODE_DISPLAY_NAME_MAPPINGS as SKELETON_IO_DISPLAY_MAPPINGS

from .process_multiple import NODE_CLASS_MAPPINGS as PROCESS_MULTI_MAPPINGS
from .process_multiple import NODE_DISPLAY_NAME_MAPPINGS as PROCESS_MULTI_DISPLAY_MAPPINGS

# Aggregate all mappings
NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

# Merge all mappings
for mappings in [LOAD_MAPPINGS, LOAD_MESH_MAPPINGS, PROCESS_MAPPINGS, PROCESS_MULTI_MAPPINGS, VIS_MAPPINGS, PREVIEW_MAPPINGS, EXPORT_MAPPINGS, SKELETON_IO_MAPPINGS]:
    NODE_CLASS_MAPPINGS.update(mappings)

for mappings in [LOAD_DISPLAY_MAPPINGS, LOAD_MESH_DISPLAY_MAPPINGS, PROCESS_DISPLAY_MAPPINGS, PROCESS_MULTI_DISPLAY_MAPPINGS, VIS_DISPLAY_MAPPINGS, PREVIEW_DISPLAY_MAPPINGS, EXPORT_DISPLAY_MAPPINGS, SKELETON_IO_DISPLAY_MAPPINGS]:
    NODE_DISPLAY_NAME_MAPPINGS.update(mappings)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
