from .Civitai_Gallery import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .Civitai_Models_Gallery import NODE_CLASS_MAPPINGS as MODELS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MODELS_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS.update(MODELS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MODELS_DISPLAY_MAPPINGS)

WEB_DIRECTORY = "./js"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']