import { defineConfig, normalizePath } from "vite";
import { readdir, unlink, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const sourceAliases = {
  "omnicam-webgl": "viewport.js",
  "omnicam-history": "director/history.js",
  "omnicam-playblast": "director/playblast.js", "omnicam-media": "director/media.js",
  "omnicam-template": "template.js",
  "omnicam-commands": "commands.js", "omnicam-state-sync": "state-sync.js",
  "omnicam-cameras": "cameras.js", "omnicam-record": "record.js",
  "omnicam-scene": "scene.js", "omnicam-timeline": "timeline.js",
  "omnicam-timeline-interaction": "timeline-interaction.js", "omnicam-curve-editor": "curve-editor.js",
  "omnicam-playback-transport": "playback-transport.js", "omnicam-motion-presets": "motion-presets.js",
  "omnicam-background-manager": "background-manager.js", "omnicam-viewport-overlays": "viewport-overlays.js",
  "omnicam-viewport-controls": "viewport-controls.js", "omnicam-event-bindings": "event-bindings.js",
  "omnicam-dom-media": "dom-media.js", "omnicam-diagnostics": "diagnostics.js",
};

// ComfyUI globs `**/*.js` under WEB_DIRECTORY and imports every hit as an
// extension, so a chunk emitted into web/ would be fetched eagerly at startup
// and code splitting would buy nothing. The bundle therefore builds into
// web-chunks/, served by omnicam/routes_chunks.py, and web/ holds only a stub
// that imports it. Keep this comment, the route module, and the stub in sync.
const STUB = `// Generated by vite.config.mjs -- do not edit.
//
// The only file ComfyUI loads as an extension. The real bundle and its lazy
// chunks live outside WEB_DIRECTORY so ComfyUI's extension glob cannot force
// them all to load; omnicam/routes_chunks.py serves them at the sibling URL
// below. The hop is relative so renaming the custom-node folder stays safe.
import "../majoor-omnicam-chunks/omnicam.js";
`;

function publicEntryStub() {
  return {
    name: "omnicam-public-entry-stub",
    resolveId(id) {
      return resolvePublicEntrySourceId(id);
    },
    async closeBundle() {
      // web/ must keep exactly one .js -- the stub -- or ComfyUI would load a
      // stale bundle from a previous single-file build alongside the new one.
      for (const file of await readdir("web")) {
        if (file.endsWith(".js")) await unlink(resolve("web", file));
      }
      await writeFile(resolve("web", "omnicam.js"), STUB, "utf8");
    },
  };
}

export function resolvePublicEntrySourceId(id) {
  // vite's normalizePath only rewrites "\" on Windows; do it unconditionally so
  // Windows-style ids resolve identically on Linux CI.
  const normalizedId = normalizePath(String(id || "").replaceAll("\\", "/"));
  const match = normalizedId.match(/(?:^|\/)omnicam-[^/]+\.js$/);
  const key = match?.[0].split("/").at(-1).replace(/\.js$/, "");
  return key && sourceAliases[key] ? normalizePath(resolve("web-src", sourceAliases[key])) : null;
}

export function normalizeModuleId(id) {
  if (!id) return null;

  const clean = normalizePath(String(id).replaceAll("\\", "/").split("?")[0]);
  if (clean.endsWith("/scripts/app.js")) return "comfyui:scripts/app.js";
  if (clean.endsWith("/scripts/api.js")) return "comfyui:scripts/api.js";

  const root = normalizePath(resolve("."));
  const rel = clean.startsWith(`${root}/`) ? clean.slice(root.length + 1) : clean;

  return rel;
}

function logicalChunkId(chunk) {
  const facade = normalizeModuleId(chunk.facadeModuleId);
  const kind = chunk.isEntry ? "entry" : chunk.isDynamicEntry ? "lazy" : "chunk";
  return `${kind}:${facade || chunk.name}`;
}

function moduleGraphAudit() {
  const outputPath = process.env.OMNICAM_VITE_GRAPH_OUT;
  if (!outputPath) return null;

  return {
    name: "omnicam-module-graph-audit",

    async generateBundle(_options, bundle) {
      const modules = [...this.getModuleIds()]
        .map(normalizeModuleId)
        .filter(Boolean)
        .sort();

      const outputChunks = Object.values(bundle).filter((item) => item.type === "chunk");
      const chunkIdByFileName = new Map(outputChunks.map((chunk) => [chunk.fileName, logicalChunkId(chunk)]));

      const chunks = outputChunks
        .map((chunk) => ({
          name: chunk.name,
          logicalId: logicalChunkId(chunk),
          facadeModuleId: normalizeModuleId(chunk.facadeModuleId),
          isEntry: chunk.isEntry,
          isDynamicEntry: chunk.isDynamicEntry,
          dynamicImports: chunk.dynamicImports
            .map((id) => chunkIdByFileName.get(id) || normalizeModuleId(id))
            .filter(Boolean)
            .sort(),
          modules: Object.keys(chunk.modules)
            .map(normalizeModuleId)
            .filter(Boolean)
            .sort(),
        }))
        .sort((a, b) => (
          String(a.facadeModuleId || a.name).localeCompare(String(b.facadeModuleId || b.name))
        ));

      const report = {
        schema_version: 1,
        platform: process.platform,
        node: process.version,
        module_count: modules.length,
        modules,
        chunks,
      };

      await writeFile(resolve(outputPath), `${JSON.stringify(report, null, 2)}\n`, "utf8");
    },
  };
}

export default defineConfig(({ mode }) => {
  const graphAudit = moduleGraphAudit();

  return {
    plugins: [
      publicEntryStub(),
      ...(graphAudit ? [graphAudit] : []),
    ],
    build: {
      emptyOutDir: true,
      lib: {
        entry: { omnicam: "web-src/main.js" },
        formats: ["es"],
        fileName: (_format, entryName) => `${entryName}.js`,
      },
      rollupOptions: {
        // ComfyUI's own modules are resolved by the browser at the URL depth the
        // chunk route mirrors, so the relative specifier is left untouched.
        external: (id) => id.startsWith("../../scripts/"),
        output: {
          // Hashed names: the chunk route serves them as ordinary static files,
          // so a new build must not reuse a URL the browser already cached.
          //
          // Third-party code keeps its vendor name in the filename. A Registry
          // heuristic that flags `.bind(` / `.connect(` inside three.js should
          // land on a file called vendor-three-<hash>.js, so a reviewer can see
          // it is upstream MIT code rather than something OmniCam wrote.
          chunkFileNames: (chunk) => (
            String(chunk.name || "").startsWith("vendor-")
              ? "[name]-[hash].js"
              : "chunk-[hash].js"
          ),
          assetFileNames: "asset-[hash][extname]",
          manualChunks(id) {
            if (id.includes("node_modules/three")) return "vendor-three";
            if (id.includes("node_modules/mediabunny")) return "vendor-mediabunny";
            return null;
          },
        },
      },
      outDir: "web-chunks",
      // Development builds ship source maps for debugging; release artifacts stay compact.
      sourcemap: mode === "development" ? true : false,
      minify: mode === "development" ? false : "esbuild",
    },
  };
});
