from .MultiText import NODE_CLASS_MAPPINGS as MULTITEXT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MULTITEXT_DISPLAY_NAME_MAPPINGS
from .TextBox import NODE_CLASS_MAPPINGS as TEXTBOX_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXTBOX_DISPLAY_NAME_MAPPINGS
from .SeamlessTexture import NODE_CLASS_MAPPINGS as ST_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ST_DISPLAY_NAME_MAPPINGS
from .AnySwitch import NODE_CLASS_MAPPINGS as SWITCH_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SWITCH_DISPLAY_NAME_MAPPINGS
from .AspectRatioPlus import NODE_CLASS_MAPPINGS as ASPECT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ASPECT_DISPLAY_NAME_MAPPINGS
from .TitlePlus import NODE_CLASS_MAPPINGS as TITLE_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TITLE_DISPLAY_NAME_MAPPINGS
from .DisplayEverything import NODE_CLASS_MAPPINGS as DISPLAY_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DISPLAY_DISPLAY_NAME_MAPPINGS
from .MultiFloat import NODE_CLASS_MAPPINGS as MULTIFLOAT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MULTIFLOAT_DISPLAY_NAME_MAPPINGS
from .comparerplus import NODE_CLASS_MAPPINGS as COMPARER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as COMPARER_DISPLAY_NAME_MAPPINGS
from .lens_flare_node import NODE_CLASS_MAPPINGS as LENS_FLARE_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LENS_FLARE_DISPLAY_NAME_MAPPINGS
from .PaintPro import NODE_CLASS_MAPPINGS as PAINT_PRO_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PAINT_PRO_DISPLAY_NAME_MAPPINGS


NODE_CLASS_MAPPINGS = {
    **MULTITEXT_NODE_CLASS_MAPPINGS,
    **TEXTBOX_NODE_CLASS_MAPPINGS,
    **ST_NODE_CLASS_MAPPINGS,
    **SWITCH_NODE_CLASS_MAPPINGS,
    **ASPECT_NODE_CLASS_MAPPINGS,
    **TITLE_NODE_CLASS_MAPPINGS,
    **DISPLAY_NODE_CLASS_MAPPINGS,
    **MULTIFLOAT_NODE_CLASS_MAPPINGS,
    **COMPARER_NODE_CLASS_MAPPINGS,
    **LENS_FLARE_NODE_CLASS_MAPPINGS,
    **PAINT_PRO_NODE_CLASS_MAPPINGS,

}

NODE_DISPLAY_NAME_MAPPINGS = {
    **MULTITEXT_DISPLAY_NAME_MAPPINGS,
    **TEXTBOX_DISPLAY_NAME_MAPPINGS,
    **ST_DISPLAY_NAME_MAPPINGS,
    **SWITCH_DISPLAY_NAME_MAPPINGS,
    **ASPECT_DISPLAY_NAME_MAPPINGS,
    **TITLE_DISPLAY_NAME_MAPPINGS,
    **DISPLAY_DISPLAY_NAME_MAPPINGS,
    **MULTIFLOAT_DISPLAY_NAME_MAPPINGS,
    **COMPARER_DISPLAY_NAME_MAPPINGS,
    **LENS_FLARE_DISPLAY_NAME_MAPPINGS,
    **PAINT_PRO_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./js"
CSS_DIRECTORY = "./css"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
    "CSS_DIRECTORY"
]