# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ComfyUI-GeometryPack Contributors

"""
Smoothing nodes
"""

from .smooth import NODE_CLASS_MAPPINGS as SMOOTH_MAPS, NODE_DISPLAY_NAME_MAPPINGS as SMOOTH_DISP
from .smooth_backends import NODE_CLASS_MAPPINGS as SMOOTH_BE_MAPS, NODE_DISPLAY_NAME_MAPPINGS as SMOOTH_BE_DISP
from .sharpen import NODE_CLASS_MAPPINGS as SHARPEN_MAPS, NODE_DISPLAY_NAME_MAPPINGS as SHARPEN_DISP
from .sharpen_backends import NODE_CLASS_MAPPINGS as SHARPEN_BE_MAPS, NODE_DISPLAY_NAME_MAPPINGS as SHARPEN_BE_DISP

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(SMOOTH_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(SMOOTH_DISP)

NODE_CLASS_MAPPINGS.update(SMOOTH_BE_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(SMOOTH_BE_DISP)

NODE_CLASS_MAPPINGS.update(SHARPEN_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(SHARPEN_DISP)

NODE_CLASS_MAPPINGS.update(SHARPEN_BE_MAPS)
NODE_DISPLAY_NAME_MAPPINGS.update(SHARPEN_BE_DISP)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
