# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 ComfyUI-GeometryPack Contributors

"""Individual Blender UV unwrap backend nodes (hidden, invoked via unified UV Unwrap node)."""

from .blender_smart import NODE_CLASS_MAPPINGS as SMART_MAPS, NODE_DISPLAY_NAME_MAPPINGS as SMART_DISP
from .blender_cube import NODE_CLASS_MAPPINGS as CUBE_MAPS, NODE_DISPLAY_NAME_MAPPINGS as CUBE_DISP
from .blender_cylinder import NODE_CLASS_MAPPINGS as CYL_MAPS, NODE_DISPLAY_NAME_MAPPINGS as CYL_DISP
from .blender_sphere import NODE_CLASS_MAPPINGS as SPH_MAPS, NODE_DISPLAY_NAME_MAPPINGS as SPH_DISP

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(SMART_MAPS)
NODE_CLASS_MAPPINGS.update(CUBE_MAPS)
NODE_CLASS_MAPPINGS.update(CYL_MAPS)
NODE_CLASS_MAPPINGS.update(SPH_MAPS)

NODE_DISPLAY_NAME_MAPPINGS.update(SMART_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(CUBE_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(CYL_DISP)
NODE_DISPLAY_NAME_MAPPINGS.update(SPH_DISP)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
