[project]
name = "comfyui-geometrypack"
description = "Warning, uses experimental package `comfy-env` to attempt a one click isolated install. Will download and use pixi package manager. CGAL - Blender - IGL - Paraview - VTK. Geometry processing nodes for ComfyUI - mesh manipulation, remeshing, hole filling, UV unwrapping, Alpha Wrapping, and 3D visualization"
version = "0.2.18"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/PozzettiAndrea/ComfyUI-GeometryPack"

[tool.comfy]
PublisherId = "pznodes"
DisplayName = "GeometryPack"
Icon = "https://raw.githubusercontent.com/PozzettiAndrea/ComfyUI-GeometryPack/main/assets/icon.png"
