"""
Musubi Tuner Wan 2.2 LoRA Training Config Template

Generates TOML dataset configuration files for wan_train_network.py
Supports Wan 2.2 T2V single-frame training with High/Low noise modes.
"""

import os


def generate_dataset_config(
    image_folder: str,
    resolution: int = 480,
    batch_size: int = 1,
    enable_bucket: bool = True,
    num_repeats: int = 10,
) -> str:
    """
    Generate a TOML dataset config file for Musubi Tuner Wan 2.2 training.

    Args:
        num_repeats: How many times to repeat each image per epoch.
                     Higher = fewer epochs for same step count, less overhead.
    Returns the config as a TOML string.
    """

    # Escape backslashes for TOML on Windows
    image_folder_escaped = image_folder.replace('\\', '/')

    config = f'''# Musubi Tuner Wan 2.2 Dataset Config
# Generated by ComfyUI Musubi Wan LoRA Trainer

[general]
resolution = [{resolution}, {resolution}]
batch_size = {batch_size}
enable_bucket = {str(enable_bucket).lower()}
caption_extension = ".txt"

[[datasets]]
image_directory = "{image_folder_escaped}"
num_repeats = {num_repeats}
'''

    return config


def save_config(config_content: str, config_path: str):
    """Save config content to a TOML file."""
    with open(config_path, 'w', encoding='utf-8') as f:
        f.write(config_content)


# Timestep ranges for Wan 2.2 High/Low/Combo noise training
# Timestep boundary for T2V is 0.875 (875 out of 1000)
# High noise: early denoising steps (timesteps 875-1000)
# Low noise: later denoising steps (timesteps 0-875)
# Combo: full range (timesteps 0-1000), use Low model
WAN_TIMESTEP_RANGES = {
    "High Noise": {
        "min_timestep": 875,
        "max_timestep": 1000,
        "description": "Trains on early denoising steps (high noise). Use with Wan 2.2 High model.",
    },
    "Low Noise": {
        "min_timestep": 0,
        "max_timestep": 875,
        "description": "Trains on later denoising steps (low noise). Use with Wan 2.2 Low model.",
    },
    "Combo": {
        "min_timestep": 0,
        "max_timestep": 1000,
        "description": "Trains on full timestep range. Use with Wan 2.2 Low model.",
    },
}


# VRAM mode presets for Wan 2.2 (Musubi Tuner)
# Wan 2.2 supports up to 1256px resolution
# blocks_to_swap is now a separate parameter (0-39)
# Note: Musubi Tuner ALWAYS requires pre-caching latents and text encoder outputs
MUSUBI_WAN_VRAM_PRESETS = {
    "Max (1256px)": {
        "optimizer": "adamw8bit",
        "mixed_precision": "fp16",
        "batch_size": 1,
        "gradient_checkpointing": False,
        "fp8_base": False,
        "resolution": 1256,
    },
    "Max (1256px) fp8": {
        "optimizer": "adamw8bit",
        "mixed_precision": "fp16",
        "batch_size": 1,
        "gradient_checkpointing": False,
        "fp8_base": True,
        "resolution": 1256,
    },
    "Medium (1024px)": {
        "optimizer": "adamw8bit",
        "mixed_precision": "fp16",
        "batch_size": 1,
        "gradient_checkpointing": True,
        "fp8_base": False,
        "resolution": 1024,
    },
    "Medium (1024px) fp8": {
        "optimizer": "adamw8bit",
        "mixed_precision": "fp16",
        "batch_size": 1,
        "gradient_checkpointing": True,
        "fp8_base": True,
        "resolution": 1024,
    },
    "Low (768px)": {
        "optimizer": "adamw8bit",
        "mixed_precision": "fp16",
        "batch_size": 1,
        "gradient_checkpointing": True,
        "fp8_base": False,
        "resolution": 768,
    },
    "Low (768px) fp8": {
        "optimizer": "adamw8bit",
        "mixed_precision": "fp16",
        "batch_size": 1,
        "gradient_checkpointing": True,
        "fp8_base": True,
        "resolution": 768,
    },
    "Min (512px)": {
        "optimizer": "adamw8bit",
        "mixed_precision": "fp16",
        "batch_size": 1,
        "gradient_checkpointing": True,
        "fp8_base": False,
        "resolution": 512,
    },
    "Min (512px) fp8": {
        "optimizer": "adamw8bit",
        "mixed_precision": "fp16",
        "batch_size": 1,
        "gradient_checkpointing": True,
        "fp8_base": True,
        "resolution": 512,
    },
}
