const langScript = document.createElement('script');
langScript.type = 'module';
langScript.innerHTML = `
import { franc,  } from 'https://cdn.jsdelivr.net/npm/franc-min@6.2.0/+esm';
window.pcFranc=franc
`;
document.head.appendChild(langScript);

export const francMap = {
  cmn: 'zh-CN',
  spa: 'es',
  eng: 'en-GB',
  rus: 'ru',
  arb: 'ar',
  ben: 'bn',
  hin: 'hi',
  por: 'pt',
  ind: 'id',
  jpn: 'ja',
  fra: 'fr',
  deu: 'de',
  jav: 'jv',
  kor: 'ko',
  tel: 'te',
  vie: 'vi',
  mar: 'mr',
  ita: 'it',
  tam: 'ta',
  tur: 'tr',
  urd: 'ur',
  guj: 'gu',
  pol: 'pl',
  ukr: 'uk',
  kan: 'kn',
  mai: 'mai',
  mal: 'ml',
  pes: 'fa',
  mya: 'my',
  swh: 'sw',
  sun: 'su',
  ron: 'ro',
  pan: 'pa',
  bho: 'bho',
  amh: 'am',
  hau: 'ha',
  fuv: 'fuv',
  bos: 'bs',
  hrv: 'hr',
  nld: 'nl',
  srp: 'sr',
  tha: 'th',
  ckb: 'ku',
  yor: 'yo',
  uzn: 'uz',
  zlm: 'ms',
  ibo: 'ig',
  npi: 'ne',
  ceb: 'ceb',
  skr: 'skr',
  tgl: 'tl',
  hun: 'hu',
  azj: 'az',
  sin: 'si',
  koi: 'koi',
  ell: 'el',
  ces: 'cs',
  mag: 'mag',
  run: 'rn',
  bel: 'be',
  plt: 'mg',
  qug: 'qug',
  mad: 'mad',
  nya: 'ny',
  zyb: 'za',
  pbu: 'ps',
  kin: 'rw',
  zul: 'zu',
  bul: 'bg',
  swe: 'sv',
  lin: 'ln',
  som: 'so',
  hms: 'hms',
  hnj: 'hnj',
  ilo: 'ilo',
  jpn: 'ja',
  kaz: 'kk',
};
