// Generated by vite.config.mjs -- do not edit.
//
// The only file ComfyUI loads as an extension. The real bundle and its lazy
// chunks live outside WEB_DIRECTORY so ComfyUI's extension glob cannot force
// them all to load; omnicam/routes_chunks.py serves them at the sibling URL
// below. The hop is relative so renaming the custom-node folder stays safe.
import "../majoor-omnicam-chunks/omnicam.js";
