from .star_video_compressor import NODE_CLASS_MAPPINGS as COMPRESSOR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as COMPRESSOR_NAMES
from .star_video_loader import NODE_CLASS_MAPPINGS as LOADER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOADER_NAMES

NODE_CLASS_MAPPINGS = {**COMPRESSOR_MAPPINGS, **LOADER_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**COMPRESSOR_NAMES, **LOADER_NAMES}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
