name: 解压工作流文件

on:
  schedule:
    - cron: '0 5 * * *'
  # 可选手动触发（推荐用于一次性操作）
  workflow_dispatch:

  # 或者在 push 到 master 分支且包含 flows.zip 时自动运行（可选）
  # push:
  #   branches: [ master ]
  #   paths:
  #     - 'comfy_flows_example/flows.zip'

# 授予必要权限（GITHUB_TOKEN 自动获得 contents 权限）
permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 保持与主同步 Action 一致

      # 配置 Git 使用 GITHUB_TOKEN 进行推送（关键！与主 Action 完全一致）
      - name: Configure Git credentials for push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Check if flows.zip exists
        id: check_file
        run: |
          wget -P ./comfy_flows_example https://material-guide-1308091668.cos.ap-beijing.myqcloud.com/flows.zip
          
          if [ -f "comfy_flows_example/flows.zip" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "flows.zip not found, skipping."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Clean directory and unzip all files (flat, no folders)
        if: steps.check_file.outputs.exists == 'true'
        run: |
          cd comfy_flows_example
      
          # 删除当前目录下除 flows.zip 外的所有内容（包括文件和子目录）
          # 注意：必须保留 flows.zip，否则无法解压
          find . -mindepth 1 ! -name 'flows.zip' -delete
      
          # 拍平解压：-j 表示 junk paths（丢弃所有目录结构）
          unzip -j -o flows.zip -x "__MACOSX/*" -x "*/.DS_Store"
      
          # 删除原始 zip
          rm -f flows.zip
      
          # 额外清理（虽然 -j 不会解压 __MACOSX，但以防万一）
          rm -rf __MACOSX
      
          cd ..

      - name: Commit and push changes (only if changes exist)
        if: steps.check_file.outputs.exists == 'true'
        run: |
          git add comfy_flows_example/
          # 检查是否有 staged changes
          if ! git diff --cached --quiet; then
            git commit -m "Auto-unzip flows.zip and remove archive"
            git push origin master
          else
            echo "No changes detected after unzip. Skipping commit."
          fi
